### DISCUSSION TITLE
Standardize Our Prettier Automatic Code Editing

### DISCUSSION THREAD

**Discussion by jbubar** [hackforla/website#1187] [General]
### Overview
In the dev meeting @trtincher and @martham0  noticed that our code extensions were changing the code in our pull requests unintentionally. We need to come up with a solution to standardize this. 

### Action Items

- [ ] Come up with a solution
- [ ] get bonnies approval
- [ ] finish writing out issue

### Resources/Instructions
Possible solutions
- github actions
- CI tools (travis ci or jenkins)
- addition to readme
- .prettierrc file

**Comment by pawan92** [comment]
This will be looked at further in break out rooms.

**Comment by jbubar** [comment]
@drubgrubby and I are going to meet this week to go over this issue

**Comment by ItsLaszlo** [comment]
Good source from @dmcneary https://mskelton.medium.com/auto-formatting-code-using-prettier-and-github-actions-ed458f58b7df

**Comment by akibrhast** [comment]
@drubgrubby @ahdithebomb @martham0 @dmcneary @hackforla/owners @ExperimentsInHonesty @pawan92 


[This](https://github.com/akibrhast/github-actions-test/pull/1) is a demo repo with GitHub action configured to run prettier on all pull request.

I believe you can check it out in action by creating a pull request with weirdly formatted js,md and json files .
_Before we add the new GitHub action to run prettier on pull request we should first run prettier on master and apply all the necessary changes_
### Blockers
- [ ] Needs approval

### Resources/Instructions
Create a GitHub action with the code snippet below
```
name: Format
on:
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md,json}

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}
```
