### ISSUE TITLE
Home Unite Us card is using different terminology for 'wanted'

### ISSUE THREAD

**Issue by cnk** [hackforla/website#1265]
### Overview
The home-unite-us.md file has catagories listed that are not part of the approved list which is messing up the display on the Looking for filter on the homepage.  We need to fix it, but we also need to stop it from happening on future tickets.

### History
- 2020/12/27 a new issue was opened with changes for the home unite us project
- On February 5th the issue was self assigned by the developer as a good first issue.
- On February 9th the following PR was made: https://github.com/hackforla/website/pull/1019 
- The relevant part of the issue is the comment here that has the looking for that the project wants to add:
https://github.com/hackforla/website/issues/953#issuecomment-761248700
`Looking: Product Manager, React Expert`
- 2021-03-19 @Cnk noticed opened this issue saying: `It says "Developer" while the other cards use "Development" and "Manager" while the other cards use "PM"`
- 2021-03-19 @akibrhast commented `@cnk This where the validation check would have been useful 🗡️  😄 `

### Action Items:
We need to 
- [x] Fix the categories on the home-unite-us.md file
- [ ] understand what the process was for how the developer decided what to put for the catagories (they are very simialar to the actual catagories)
- [ ] understand how did the PR get past the person reviewing it and what do we look for when we review changes on the project cards
- [ ] figure out how to change our process so that the categories are adhered to.
   - [ ] How might we ensure the the categories used are the ones that are approved?
   - [ ] How might we automate as much of this as possible?

### Details
https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/home-unite-us.md
Has the following:
```
looking: 
  - category: UI/UX
    skill: UI (including wireframes, familiar with Figma)
  - category: Manager
    skill: Product Manager
  - category: Developer
    skill: React Expert
```

I think this in part because we have not made a guide to how to put these items in the project.md file. I looked at the template in our wiki and it does not have a full list: https://github.com/hackforla/website/wiki/Template-of-a-project.md-file
```
looking:
  - category: Development
    skill: one skill
  - category: UI/UX
    skill: another skill
  - category: Content
    skill: Researcher
```
Here is the list of allowable categories
- Business Analyst
- Content
- Data
- Development
- Ops
- PM
- QA
- SEO/Marketing
- UI/UX

But here is what we have now because we have not enforcing the set list of categories
![Screen Shot 2021-03-24 at 4 20 05 PM](https://user-images.githubusercontent.com/37763229/112396120-d928c480-8cbc-11eb-913a-9ecfc0f1a68c.png)

**Comment by akibrhast** [comment]
@cnk This where the validation check would have been useful 🗡️  😄

**Comment by ExperimentsInHonesty** [comment]
https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/home-unite-us.md
Has the following:
```
looking: 
  - category: UI/UX
    skill: UI (including wireframes, familiar with Figma)
  - category: Manager
    skill: Product Manager
  - category: Developer
    skill: React Expert
```

I think this in part because we have not made a guide to how to put these items in the project.md file. I looked at the template and it does not have a full list: https://github.com/hackforla/website/wiki/Template-of-a-project.md-file
```
looking:
  - category: Development
    skill: one skill
  - category: UI/UX
    skill: another skill
  - category: Content
    skill: Researcher
```
