### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1302]
```yaml
                                identification: '76137532'
title: HelloGOV
description: >-
  HelloGOV is helping grassroots organizations connect supporters to their state
  assembly and state senate representatives for call campaigns to advocate on
  the legislation that matters most to their work. The HelloGOV webapp generates
  a campaign shortlink that can be used in texts, social posts, and more.
image: /assets/images/projects/hellogov.jpg
image-hero: /assets/images/projects/hellogov-hero.jpg
alt: Smartphones using hellogo app
leadership:
  - name: Kate Rose
    picture: https://avatars.githubusercontent.com/kate-rose
    links:
      github: https://github.com/kate-rose
      slack: https://hackforla.slack.com/team/UA02Y8W2Z
  - name: Sarah Port
    picture: https://avatars.githubusercontent.com/seport
    links:
      github: https://github.com/seport
      slack: https://hackforla.slack.com/team/U686ZV93P
  - name: Brett Beekley
    picture: https://avatars.githubusercontent.com/beekley
    links:
      github: https://github.com/beekley
      slack: https://hackforla.slack.com/team/USRRN73NE
links:
  - name: GitHub
    url: https://github.com/helloGov/
  - name: Site
    url: https://hellogov.squarespace.com
  - name: Readme
    url: https://github.com/helloGov/webapp/blob/master/README.md
  - name: Slack
    url: https://hackforla.slack.com/archives/CMER3R1RD
location:
  - Santa Monica
  - Remote
partner: Digital Defense Fund
tools: Mongo, Angular, Node, JS
vertical: Vote / Representation
status: Active

                            ```
