### ISSUE TITLE
Project Profile Card Review and Update

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1303]
```yaml
         identification: '190321758'
title: 311 Data
description: >-
  The 311 Data project seeks to empower local Neighborhood Councils to improve
  the ideation and analysis of their initiatives using the wealth of publicly
  available 311 data.
image: /assets/images/projects/311_data.png
image-hero: /assets/images/projects/311data-beta.png
alt: Image of building with windows that look like they spell out 311.
leadership:
  - name: Dana Chen
    role: UI/UX Senior Lead
    picture: https://avatars.githubusercontent.com/danarchen
    links:
      github: https://github.com/danarchen
      slack: https://hackforla.slack.com/team/U0112KZPV6C
  - name: Kevin Perez
    role: UI/UX Lead
    picture: https://avatars.githubusercontent.com/kevindperez
    links:
      github: https://github.com/kevindperez
      slack: https://hackforla.slack.com/team/U011K0F02M9
  - name: Adam Kendis
    role: Frontend Lead
    picture: https://avatars.githubusercontent.com/adamkendis
    links:
      github: https://github.com/adamkendis
      slack: https://hackforla.slack.com/team/USNAHR0KE
  - name: Matt Webster
    role: Backend Lead
    picture: https://avatars.githubusercontent.com/mattyweb
    links:
      github: https://github.com/mattyweb
      slack: https://hackforla.slack.com/team/URLNVEEB0
links:
  - name: GitHub
    url: https://github.com/hackforla/311-data
  - name: Slack
    url: https://hackforla.slack.com/archives/CJY4R382X
  - name: Wiki
    url: https://github.com/hackforla/311-data/wiki
  - name: Join Us
    url: https://github.com/hackforla/311-data/wiki/Joining-the-311-Team
  - name: Site
    url: https://www.311-data.org/
location:
  - Downtown LA
  - Remote
looking:
  - category: Business Analyst
    skill: Business Analyst
  - category: Ops
    skill: Project Manager
  - category: Development
    skill: Frontend Developers
  - category: Development
    skill: Backend Developers
  - category: Ops
    skill: Product Owner
technologies:
  - ReactJS
  - Redux
  - Material-UI
  - Mapbox
  - AWS
  - Python
  - FastAPI
  - Redis
  - PostgreSQL
  - Prefect
  - Docker
  - Figma
  - Adobe CC
  - Miro
partner: EmpowerLA
vertical: Citizen Engagement
status: Active

                  ```
