### ISSUE TITLE
button default

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1352]
### Overview
In the site guide, there is a btn class for all buttons. Would it be better to make this a default on all <button> html elemnts?
This issue is to figure that out.

### Action Items
- [ ] look into <button> html elements
- [ ] look into where .btn is used
- [ ] come up with a proposal and share it with UI/UX and the dev team.

### Resources/Instructions
```css
.btn {
  border: 0;
  box-shadow: 0 0 8px 0 rgba($color-black, 0.2);
  display: inline-block;
  font-weight: map-get($font-weight, bold);
  text-decoration: none;
  transition: all 100ms ease-in;
  white-space: nowrap;
  margin: 0 20px 20px 0;
}
- https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3686%3A93
```
