### ISSUE TITLE
Feasibility: Test out the new issue forms

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2128]
### Overview

As an admin on the team, we need to find the ways in which we can leverage the new issue forms feature of GH for our purposes. 

### Action Items
- [x] Research the new [issue forms feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).
- [x] In the below Feasibility Tests, tick off features that are confirmed to be possible.
- [x] Create a demo that shows all the features that are ticked off below.
  - [x] If any cool features are not tested below, but it seems useful, please feel free to demo that as well! 
- [x] In a second demo, recreate our blank issue template as an issue form as closely as possible.
- [x] Showcase the demos at a meeting. Be sure to ask to have the demo added to the agenda!

### Feasibility Tests

- [ ] Can issue forms pull existing data from our repo into the form?
- [ ] Can issue forms pull existing external data (not from our repo) into the form?
- [ ] Can issue forms limit the length of text in an input?
- [x] Does issue forms support:
  - [x] Check boxes?
  - [ ] Radios?
  - [ ] Buttons?
  - [x] Small Input?
  - [x] Textarea Input? 
  - [x] Required inputs?
- [x] Can issue forms pre-label certain templates?
- [x] Can issue forms pre-populate a template with static text?
- [ ] Can issue forms verify if responses is in a certain format?
  - [ ] If so, how? 
- [x] What input types does issue forms allow?

### Resources/Instructions
[Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
Akib's test [template](https://github.com/akibrhast/website/blob/gh-pages/.github/ISSUE_TEMPLATE/bug.yml)
[new issue sample](https://github.com/akibrhast/website/issues/new?assignees=octocat&labels=bug%2Ctriage&template=bug.yml&title=%5BBug%5D%3A+)
[blank issue template](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-.md)
[blank issue raw file ](https://raw.githubusercontent.com/adrian-zaragoza/website/gh-pages/.github/ISSUE_TEMPLATE/demo_blank_issue.yml)
[features raw file](https://raw.githubusercontent.com/adrian-zaragoza/website/gh-pages/.github/ISSUE_TEMPLATE/demo_features.yml)

**Comment by ExperimentsInHonesty** [comment]
Draft that Akib made
```
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
```
