### ISSUE TITLE
Convert Blank Issue Template to Github Form Issue

### ISSUE THREAD

**Issue by adrian-zaragoza** [hackforla/website#2283]
### Overview
As an issue creator, we want to implement issue templates for issue creation to streamline and simplify the process. The current issue forms require the person to replace the text, and is less user-friendly compared to GitHub Form issues.

### Action Items

- [ ] Create a blank-issue-form.yml file in this [folder ](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
- [ ] Add the code below to the file.
```
name: 'Blank Issue '
description: 'Standard HackforLA issue template '
title: ''
labels: ''
assignees: ''

body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
    validations:
      required: true
  - type: dropdown
    id: dependency
    attributes:
      label: Is there a dependency?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: dependency-explanation
    attributes:
      label: If Yes, please explain
```

- [ ] Rename the current blank-issue-.md file to blank-issue-template.md.

### Resources/Instructions
[Github Issue Forms Reading](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Github Issue Forms Reading Pt2](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
[#2128 ](https://github.com/hackforla/website/issues/2128)

**Comment by Aveline-art** [comment]
Hi @adrian-zaragoza . Sorry to make this more complicated, but I just remember that there also needs to be a Dependency portion to the issue form. The way it works would be akin to:

- [ ] Is there a dependency?
- [ ] If yes, please specify ________

Can you add this in? I know this might be a hassle, since this is a good first issue.

**Comment by ExperimentsInHonesty** [comment]
@adrian-zaragoza I removed the Ready for Milestone label.  Please address what Ava said above.  

@macho-catt  Good First Issues and Good Second issues need to be explicit, and it seems that there is part of the issue that opens up the possibility of doing something other than the instructions at the top.  The decision about doing the optional action should be made before this issue is released.  Or the issue will need to be moved to a higher level, such as medium (appropriate for someone to champion the dialog after they know how to do PRs on our project).

**Comment by adrian-zaragoza** [comment]
Hi @Aveline-art and @ExperimentsInHonesty I have updated the code block on the issue comment and added a dropdown with "Yes" and "No" for Is there a dependency?. I also added a textbox to explain further if there is a dependency. 
Does the dependency portion need to be added to the other github issue forms? If so, which ones?

I ran the code in my repo and this is how the form looks like.
<details>
  <summary>After Changes Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/77212035/134750242-6173c2a6-1244-4fee-863e-efb9aa792f37.png" >
</details>

**Comment by Aveline-art** [comment]
@adrian-zaragoza I believe the blank issue form will suffice for now. Just to be sure, an issue with a dependency will ultimately look like #2266. I know the exact format might not be possible with issue forms, but we can play around once the form has been uploaded and created.

**Comment by macho-catt** [comment]
We can remove the context and feedback areas for now and create a future issue to add these options. I will update the post so that this can be labelled as a good second issue.

I am also editing the requirements so that instead of deleting the old blank-issue-.md file, we keep it and rename it to blank-issue-template.md. Then we make the new form to be blank-issue-form. That way if we ever want to go back to that template, we still have it. Additionally, there may be some people who prefer creating issues using that template (like me :D).

Saving the code block here so we can use it for a future issue:

<details>
<summary>Saved text</summary>

One idea that came out from a meeting was adding an additional textarea to the form for "Context" to describe the bug in more detail, like the steps the person took to receive the error. Another idea was adding a textarea for feedback. If this is something we want to include, we would need to include the below code in addition to the code above.

```
  - type: textarea
    id: comments
    attributes:
      label: "Context"
      description: "Please provide any additional information to describe how you came about this issue if any."
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: "Feedback"
      description: "Feedback to improve the issue creation process"
    validations:
      required: false
```

</details>
