### ISSUE TITLE
Convert Communities of Practice information updates Template to Github Form Issue

### ISSUE THREAD

**Issue by adrian-zaragoza** [hackforla/website#2291]
### Dependency
~~https://github.com/hackforla/website/issues/2202~~

### Overview
As an issue creator, we want to implement issue templates for issue creation to streamline and simplify the process. The current issue forms require the person to replace the text, and is less user-friendly compared to GitHub Form issues.

### Action Items
- [ ] Create a new communities-of-practice-information-updates-form.yml file in your own fork in: ```gh-pages/.github/ISSUE_TEMPLATE``` based on the current [communities-of-practice-information-updates.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.md)
- [ ] Check the dropdown below to see a sample of how it should look like
- [ ] Follow github form syntax readings below to code a similar form to the [current issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=role%3A+product&template=communities-of-practice-information-updates.md&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice).
- [ ] Test the new issue template on your own fork and make sure it works
- [ ] Delete communities-of-practice-information-updates.md file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)

**Sample Code**
<details>
<summary>Click dropdown</summary>

```
name: Demo Communities of Practice information updates
description: Template for CoP leads to review and update the Name, Description. Leadership
  Type, Leadership members, Slack in order keep the community of practice page on
  the website up to date.
title: 'Communities of Practice information updates: [INSERT NAME OF Community of
  Practice]'
labels: ['role: product']

body:
  - type: markdown
    attributes:
      value: "### Overview"
  - type: markdown
    attributes:
      value: "As a Community of Practice Co-Lead, I need my CoP's details to be up to date on the HackforLA website."
  - type: markdown
    attributes:
      value: "### Action Items"
  - type: markdown
    attributes:
      value: "Change CoP name: NO"
  - type: markdown
    attributes:
      value: "Change Description: NO"
  - type: markdown
    attributes:
      value: "Change Leadership Type: NO"
  - type: markdown
    attributes:
      value: "Change Slack Link: NO"
  - type: dropdown
    id: remove-person-yes-no
    attributes:
      label: "Remove person(s) and info from CoP file?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: remove-person
    attributes:
      label: "If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:"
      value: "Name:"
  - type: dropdown
    id: add-person-yes-no
    attributes:
      label: "Add person(s) and info to CoP file?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: add-persons
    attributes:
      label: "If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:"
      value: |
        Name:
        Title:
        GitHub Handle:
        Slack Member ID:
  - type: markdown
    attributes:
      value: "### Resources"
  - type: markdown
    attributes:
      value: |
        folder where files are in the repo: https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities
        where you can see the live page: https://www.hackforla.org/communities-of-practice
```

</details>

### Resources/Instructions
- Related demo issue: #2202
- [Current Issue Template Code File](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.md)
- [Github Forms Issue Reading](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
- [Github Forms Issue Reading Pt 2](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
- #2128
