### ISSUE TITLE
Add Giving icon to Credits Page

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2356]
### Overview
We need to add the Give image to the Credits page so that we can maintain image use compliance standards

### Action Items
- [x] In your editor, go to `_data/internal/credits` folder and create a file called `giving.yml`
- [x] Fill in the `giving.yml` file with the following code
```yaml
---
title: Giving
title-link: https://thenounproject.com/search/?q=heart+hand&i=3364926
content: icon
used-in: About Us
artist: Nawicon
provider: Noun Project
provider-link: https://thenounproject.com/
image-url: /assets/images/about/platform-header-elements/giving.svg
alt: 'Heart in hand'
type: icon
---
```
- [x] Save the updated `giving.yml` file and verify you can see the Giving icon in the Credits page
- [x] Once you have verified, make a pull request for final review 

### Resources/Instructions
[Figma design for reference - look for Give icon](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7432%3A39843)
https://github.com/hackforla/website/wiki/Credits-yml-file-template
