### ISSUE TITLE
Update Project Profile: Open Community Survey

### ISSUE THREAD

**Issue by jonarcisse** [hackforla/website#2364]
### Overview
We need to update the Open Community Survey project so that we provide the end-user with accurate and up-to-date information.

### Action Items

- [x] **Remove** the following people from the **leadership** property:
https://github.com/hackforla/website/blob/28e0442c16482fbd21171604402e93cd94099e2a/_projects/open-community-survey.md#L22-L27
- [x] **Add** the following people from the **leadership** property:
```
- name: Sonu 
  role: Data Analyst
  links:
    slack: 'https://hackforla.slack.com/team/U027JBTAGSX'
    github: 'https://github.com/sonu-k'
  picture: https://avatars.githubusercontent.com/sonu-k

- name: Snow
  role: UX Researcher
  links:
    slack: 'https://hackforla.slack.com/team/U029J3LT0TS'
    github: 'https://github.com/LAStorm'
  picture: https://avatars.githubusercontent.com/LAStorm

- name: Amy Wilkins
  role: UX Researcher
  links:
    slack: 'https://hackforla.slack.com/team/U0231JD5BC2'
    github: 'https://github.com/amy-c-w'
  picture: https://avatars.githubusercontent.com/amy-c-w

- name: Jasmine Kim
  role: UX Researcher
  links:
    slack: 'https://hackforla.slack.com/team/U02AYE78X1Q'
    github: 'https://github.com/jaskim20'
  picture: https://avatars.githubusercontent.com/jaskim20

- name: JoAnne Narcisse
  role: Product Manager
  links:
    slack: 'https://hackforla.slack.com/team/U02AHBLDJ15'
    github: 'https://github.com/jonarcisse'
  picture: https://avatars.githubusercontent.com/jonarcisse

- name: Shika Zhou
  role: Data Analyst
  links:
    slack: 'https://hackforla.slack.com/team/ U029BAPRTA8'
    github: 'https://github.com/ShikaZzz'
  picture: https://avatars.githubusercontent.com/ShikaZzz
```
      
#### File and Code links you will need to review this issue
- Directory to find the page once you have it in your IDE: `_projects/open-community-survey.md`

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/28e0442c16482fbd21171604402e93cd94099e2a/_projects/open-community-survey.md#L1-L63
