### ISSUE TITLE
Update Project Profile: Civic Tech Index

### ISSUE THREAD

**Issue by DrIffathsultana** [hackforla/website#2386]
### Overview
We need to update the Civic Tech Index project so that we can provide end-users with up to date 

### Action Items

- [x]  **Remove line 23-28** from `projects/civic-tech-index.md`
https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L23-L28
- [x]  **Remove line 41-46** from `projects/civic-tech-index.md`
https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L41-L46
- [x]  **Remove line 71-76** from `projects/civic-tech-index.md`
https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L71-L76
- [x]  **Remove line 77-82** from `projects/civic-tech-index.md`
https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L77-L82
- [x]  **Remove line 83-88** from `projects/civic-tech-index.md`
https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L83-L88
- [x]  **Remove line 113-118** from `projects/civic-tech-index.md`
 https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L113-L118
- [x]  **Remove line 119-124** from `projects/civic-tech-index.md`
 https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L119-L124
  - [x]  **Remove line 125-130** from `projects/civic-tech-index.md`
 https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L125-L130
  
- [x] **Add** the following names to the `leadership` property within `projects/civic-tech-index.md`
```
  - name: Levi Adissi 
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/UD9MQDARJ'
      github: 'https://github.com/ladissi'
    picture: https://avatars.githubusercontent.com/ladissi
  - name: Kevin Phan
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U02B90U9FPS'
      github: 'https://github.com/kevindphan'
    picture: https://avatars.githubusercontent.com/kevindphan
  - name: Shipra Prakash
    role: UX/UI Designer
    links:
      slack: 'https://hackforla.slack.com/team/U01TUA963NZ'
      github: 'https://github.com/shipranj'
    picture: https://avatars.githubusercontent.com/shipranj
  - name: Farzana Prianka
    role: UX/UI Designer
    links:
      slack: 'https://hackforla.slack.com/team/U01FUP87W3U'
      github: 'https://github.com/FarzanaPrianka'
    picture: https://avatars.githubusercontent.com/FarzanaPrianka
```

### Resources
https://www.hackforla.org/projects/civic-tech-index
https://github.com/hackforla/website/blob/68ecfb601f6aa7a5b2be52d53768ba70e320b47d/_projects/civic-tech-index.md#L1-L158
