### ISSUE TITLE
Update partners.yml so each partner have a program-area property

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2459]
### Dependency
This issue will be able to be closed when the following issues are completed
- ~#2271~
- ~#2384~

### Overview
We need to update our data files so liquid references become easier to implement. 

### Action Items
- [x] For each partner in the partners.yml file, add a new property called `program-area` and add the proper program-area value(s) in that field

<details>
<summary>Example for a partner with multiple program-areas</summary>

```
- name: Code for America
  image: /assets/images/about/sponsors/code-for-america.svg
  link: https://www.codeforamerica.org/
  program-area:
    - Citizen Engagement
    - Civic Tech Infrastructure
```

</details>

<details>
<summary>Example for a partner with a single program-area</summary>

```
- name: Ballotpedia
  image: /assets/images/about/partners/bp.png
  link: https://ballotpedia.org/Main_Page
  program-area:
    - Vote / Representation
```

</details>

### Resources/Instructions
The current partner.yml file does not have the program areas field.
The New version needs a program area's field.
This [comment](https://github.com/hackforla/website/issues/2459#issuecomment-974919932) has the replacement content.

[partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml)
[Program Area Audit](https://docs.google.com/spreadsheets/d/1wkzmWck-aGTzGxiryYEUhGbKRJX8rDDT3RLsAn-E-9o/edit#gid=0)
