### ISSUE TITLE
Add GitHub link to community of practice: Project/Product Management

### ISSUE THREAD

**Issue by adrian-zaragoza** [hackforla/website#2489]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to update the community of practice GitHub links so we can provide the end-user with more information about our communities.

### Action Items
- [x] Add the following lines on line 32 of the file `_data/internal/communities/project-management.yml`:
```
  - name: Github
    url: https://github.com/hackforla/product-management
```
So that the end result looks like this:
```
links:
  - name: Slack
    url: https://app.slack.com/client/T04502KQX/C010LNXH2JY/details/
  - name: Github
    url: https://github.com/hackforla/product-management
```
- [x] Ensure that the Communities of Practice page on your local environment reflects your changes
    - [x] The local environment url will be localhost:4000/communities-of-practice
    - [x] A "View GitHub" button should appear on the Project/Product Management page card after the change
    - [x] Clicking the button should resolve to the Product Management GitHub repository

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_data/internal/communities/project-management.yml`
- [Communities of Practice page](https://www.hackforla.org/communities-of-practice)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/6c445b6d092b73ec6457a989fce587e20bc133e2/_data/internal/communities/project-management.yml#L29-L32
