### ISSUE TITLE
Update the Current Project Team Section for HfLA Website Project

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2544]
### Overview
We need to update the project team section of the HFLA Website project page to properly reflect the current members of the leadership team.

### Details
We need to remove Mathew Cacho, Sihem Gourou, Kristine Eudey and add Tomas Gonzalez, Saumil Dhankar, Isaac Cruz, and Simone Campbell on the Website team project page leadership section.

### Action Items
- [x] Remove Mathew Cacho and add Tomas Gonzalez, Saumil Dhankar as Technical Leads on the HfLA Team. Change the links accordingly as well.
    - **Edit Technical Lead section** under `_projects/website.md`

Changes required in the following section:
```
  - name: Matthew Cacho
    role: Technical Lead
    links:
      slack: 'https://hackforla.slack.com/team/U0262GA4DD2'
      github: 'https://github.com/macho-catt'
    picture: https://avatars.githubusercontent.com/macho-catt
```

- [x] Remove Sihem Gourou as Product Manager on the HfLA Team
    - **Remove Product Manager section** under `_projects/website.md`

Remove the following section:
```
  - name: Sihem Gourou
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U021GM545UG'
      github: 'https://github.com/Sihemgourou'
    picture: https://avatars.githubusercontent.com/Sihemgourou
```

- [x] Remove Kristine Eudey and add Isaac Cruz as UX Design Lead on the HfLA Team. Change the links accordingly as well.
    - **Edit UX Design Lead section** under `_projects/website.md`

Changes required in the following section:
```
  - name: Kristine Eudey
    role: UX Design Lead
    links:
      slack: 'https://hackforla.slack.com/team/U0252CHL678'
      github: 'https://github.com/kristine-eudey'
    picture: https://avatars.githubusercontent.com/kristine-eudey
```

- [x] Add Simone Campbell as UX Research Lead on the HfLA Team
    - **Add UX Research Lead section** under `_projects/website.md`

Add the following section:
```
  - name: Simone Campbell
    role: UX Research Lead
    links:
      slack: 'https://hackforla.slack.com/team/U0260MKR5EJ'
      github: 'https://github.com/sacamp'
    picture: https://avatars.githubusercontent.com/sacamp
```

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/website.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Website page](https://www.hackforla.org/projects/website)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/website.md?plain=1
