### ISSUE TITLE
Update leadership and technologies in website.md

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2731]
### Overview
As a member of the Hack for LA Website team, I want the information on the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website) to be up to date. For this issue, we will be updating the leadership and technologies sections of the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website).

### Action Items
In [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md), complete the following:
- [x] Under the [leadership section](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1#L9),
  - [x] Remove the information for Tomas Gonzalez [on lines 22-27](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1#L22-L27)
  - [x] Add the following information for Jessica Cheng
  ```
    - name: Jessica Cheng
      role: Technical Lead
      links:
        slack: 'https://hackforla.slack.com/team/U02NWK24H3N'
        github: 'https://github.com/JessicaLucindaCheng'
      picture: https://avatars.githubusercontent.com/JessicaLucindaCheng
  ```
  - [x] Add the following information for Providence Onyenekwe
  ```
    - name: Providence Onyenekwe
      role: Product Manager
      links:
        slack: 'https://hackforla.slack.com/team/U02TECJJ3R7'
        github: 'https://github.com/Providence-o'
      picture: https://avatars.githubusercontent.com/Providence-o
  ```
- [x] Under the [technologies section](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1#L66), add the following technologies:
```
  - Google Apps Script
  - GitHub Actions
  - VRMS API
```

### Resources/Instructions
- [Hackforla.org Website project information page](https://www.hackforla.org/projects/website)
- Changes for technologies can also be seen on the Hackforla.org Website project card on the [project page](https://www.hackforla.org/projects/)
- [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md)
