### ISSUE TITLE
Project.md file format changes log

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#294]
### Overview
This issue contains all proposals for changes to the project.md files (including links to their relevant discussions) and dependencies.  

### Action Items
[ ] Post vetted proposal to comment
[ ] Assign reviewers
[ ] Indicate if there are Template Issue dependencies, and if so which
[ ] Once approved create issue using [template](https://github.com/hackforla/website/issues/new?assignees=&labels=documentation%2C+enhancement&template=proposal-to-change-project-md-file-format.md&title=Proposal+to+change+project.md+file+format+%5Bthat+accomplishes+x%5D)
 
### Resources/Instructions
Temple issue - [create new project](https://github.com/hackforla/.github/blob/master/.github/ISSUE_TEMPLATE/create-project-card-for--project-name-.md)
Template issue - [update project profile](https://github.com/hackforla/.github/blob/master/.github/ISSUE_TEMPLATE/update-project-profile---name-of-project-.md)

**Comment by ExperimentsInHonesty** [comment]
### Proposal Title
Proposal to change project.md file format to create uniform links across projects

### Proposal summary
We need a way to tell the project homepage which links to render at the top, and be able to add or remove links in the future.  This should be across all project homepages.

### Current state
engage.md has the following
```yaml
links: 
  - name: Github
    url: 'https://github.com/hackla-engage'
  - name: Site
    url: 'https://sm.engage.town'
```
public-tree-map.md has the following:
```yaml
links: 
  - name: Github
    url: 'https://github.com/Public-Tree-Map/'
  - name: Test Site
    url: 'http://public-tree-map.surge.sh/'
  - name: Slack
    url: 'https://hackforla.slack.com/messages/C9UU5KKAA/'
  # - name: Site
  #   url: ''
```
### Future state
change project.md files to use this format
```yaml
links: 
  - name: Github
    url: 'https://www.example.com'
  - name: Slack
    url: 'https://www.example.com'
  - name: Testing Site
    url: 'https://www.example.com'
# unused links that require specific naming should remain in file and be commented out if unused
  # - name: Live Site
  #   url: ''
```

### Dependencies
None

### Reviewers requested 
@thekaveman 

### Discussion location
1. https://github.com/hackforla/website/issues/157#issuecomment-582546238
2. https://github.com/hackforla/website/issues/157#issuecomment-582548902
3. https://github.com/hackforla/website/issues/157#issuecomment-582612863
4. https://github.com/hackforla/website/issues/157#issuecomment-582644033
