### ISSUE TITLE
Credits page: Add SoGoSurvey for the Design Systems team

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3022]
### Overview
As a member of Hack for LA, I want to add SoGoSurvey to the [Credits page](https://www.hackforla.org/credits/) so that the Design Systems team will have access to SoGoSurvey's Plus plan for free. For this issue, we will update the [Credits page](https://www.hackforla.org/credits/) to include a new type of credit and add SoGoSurvey to the page.

### Screenshots
Below are screenshots of the updates but please reference the [Credits page Figma design in the blue box](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0) when working on this issue to see details more clearly.

<details>
  <summary>The new paragraph text in the header section under "Credits" and the new "Iconography and Imagery" h2 header</summary>
   
  Desktop
  <img width="764" alt="updated-credits-header-paragraph-and-h2-iconography" src="https://user-images.githubusercontent.com/31293603/161354589-59c553fd-818b-4f8c-9970-3e4a2a585621.png">
   
  Mobile
  <img width="232" alt="mobile-updated-credits-header-paragraph-and-h2-iconography" src="https://user-images.githubusercontent.com/31293603/161354347-1cda5d46-ba23-4c94-8390-36641e115ae2.png">

</details>

<details>
  <summary>The new Tools section</summary>
  
  Desktop
  <img width="765" alt="updated-credits-with-tools-section" src="https://user-images.githubusercontent.com/31293603/161354818-4c889e4b-8569-43c9-8a45-34e7f6a0a90f.png">

  Mobile
  <img width="230" alt="mobile-updated-credits-with-tools-section" src="https://user-images.githubusercontent.com/31293603/161354848-e0f60cff-50c1-41e9-a91b-570de64c462f.png">
  
</details>

### Action Items
- [x] Download the [SoGoSurvey logo](https://www.sogosurvey.com/static/ONLINE-SURVEY-IMAGES/ONLINE-SURVEYS-COMMON/logoM.png)
- [x] Rename the image to `so-go-survey`
- [x] Add the image to the [assets/images/credits](https://github.com/hackforla/website/tree/gh-pages/assets/images/credits]) directory
- [x] Create a new folder in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) named `tools`
- [x] Create a credit file called `so-go-survey.yml` in the `tools` folder you created
  - [x] Add the following to the `so-go-survey.yml` file:
    ```
    ---
    # The company, organization, or individual providing the tool
    tool-provider: SoGoSurvey
    # Please give the general site URL for the tool provider
    provider-link: https://www.sogosurvey.com/
    # Location in our GitHub repo of the tool's logo
    logo-url: /assets/images/credits/so-go-survey.png
    # The type of tool, such as a survey
    tool-type: survey
    # The area it is used in - Research, Development, Design, Product Management, etc
    used-in: Research
    # A list of the project team(s) using the tool
    used-by:
        # Name of a project team
      - project-name: Design System's Team
        # Link to the project team's page
        project-link: https://www.hackforla.org/projects/design-systems
    ---
    ```
In [pages/credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html),
- [x] Change the paragraph header text to the new paragraph header text
- [x] Add the h2 header for `Iconography & Imagery`
- [x] Put the code for an image credit in an if block by
  - [x] Adding the line of code `{%- if item[1].image-url -%}` after
    https://github.com/hackforla/website/blob/f0e7431e3366daae140dc2b46df3a7d3d006070b/pages/credits.html#L25
  - [x] Adding the line of code `{%- endif -%}` after
    https://github.com/hackforla/website/blob/f0e7431e3366daae140dc2b46df3a7d3d006070b/pages/credits.html#L64
  - [x] Make sure to add appropriate indentation for the code in the if block
- [x] At the bottom of the page, create a new section for Tools
  - [x] Make sure to add the h2 header for Tools
  - [x] Add the SoGoSurvey credit to this section
    - [x] The alt text for the SoGoSurvey logo image should be `alt=""`. (For why it is alt="", see this https://github.com/hackforla/website/issues/2936#issuecomment-1076770029 and [WCAG tutorial on decorative images](https://www.w3.org/WAI/tutorials/images/decorative/))
- [x] To style the page, adjust or add styling in [_sass/components/_credit-items.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_credit-items.scss). However, try to use existing classes/styling in our codebase as much as possible, especially Design System reusable components which you can see the components and their classes in [Design Systems in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3).
- [x] Check the page looks good in mobile, tablet, and desktop views using developer tools
- [x] Reach out to the Design Systems team member, Jeanette (GitHub handle JeannyRen), to let them know after the PR is merged. You can do that by posting on this issue https://github.com/hackforla/design-systems/issues/350

### Resources/Instructions
- [Credits page](https://www.hackforla.org/credits/)
- [Credits page Figma design in the blue box](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0)
- [SoGoSurvey logo](https://www.sogosurvey.com/static/ONLINE-SURVEY-IMAGES/ONLINE-SURVEYS-COMMON/logoM.png)
- [assets/images/credits](https://github.com/hackforla/website/tree/gh-pages/assets/images/credits]) directory
- [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits)
- [pages/credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html)
- Related design issue: https://github.com/hackforla/website/issues/2936
- Related Design Systems team's issue: https://github.com/hackforla/design-systems/issues/350
- [WCAG tutorial on headings](https://www.w3.org/WAI/tutorials/page-structure/headings/)
- [WCAG tutorial on decorative images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [Design Systems in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
- [Liquid templating language](https://jekyllrb.com/docs/liquid/)
