### ISSUE TITLE
Update toolkit yml files to include a new fields

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3357]
### Overview
We need to add new fields and change a field to the Internal and External Resources files for the toolkit, so that we can have filters similar to what exists on the homepage.

### Action Items
- [x] Add the field to all files listed below
- [x] identify which files need info for the new fields and add them to a comment on this issue, so that the Guides team can provide the information.  Bring this to Sunday meeting with product.
- [x] Change the name of category and update the code that displays the toolkit page results when you click on Development on the ribbon menu
- [x] update wiki template example ([created this one](https://github.com/hackforla/website/wiki/Toolkit-files-template))

### Additional Fields needed
tools (Figma, GitHub, Miro, etc.)
contributors (for internal guides all contributors will be listed)
source (Hack for LA, Code for America, Other)

### Change the name of these fields
from `category` to `practice-area`

### Current Fields for items showing up on the https://www.hackforla.org/toolkit/ as `External Resources`
```
title: Figma
  description: Our design team uses Figma to create wireframes and mockups.
  svg: svg/icon-figma.svg
  link-svg: svg/outer-link.svg
  provider-link: 'https://www.figma.com/'
  display: true
```
### Current Fields for items showing up on the https://www.hackforla.org/toolkit/ as `Guides`
```
title: 2FA Guide
description: Hack for LA requires two-factor authentication (2FA) in GitHub for all project contributors.
short-description: Hack for LA requires two-factor authentication (2FA) in GitHub for all project contributors.
in-this-guide:
  - name: To Enable 2FA
    link: '#To-Enable-2FA'
  - name: FAQ
    link: '#FAQ'
card-type: guide-page
status: active
display: true
category: Development
svg: svg/2FA.svg
provider-link: '/guide-pages/2FA'
```

- https://www.hackforla.org/toolkit/
- https://github.com/hackforla/website/blob/gh-pages/_data/internal/toolkitresources.yml
- https://github.com/hackforla/website/tree/gh-pages/_guide-pages
- [spreadsheet from guides team](https://docs.google.com/spreadsheets/d/1WbACQLJO4WnA7qlc74xuPrsol9-Y1YcJ8y30hu3Ty9c/edit#gid=2026961647)
