### ISSUE TITLE
Creating a yml file for SDG 11

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4293]
### Overview
We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.

### Action Items
- [x] In `_data/internal/sdg`, add a file called `sdg11.yml`
- [x] In the file you just created, add the following:
```
# The Sustainable Development Goal (SDG) number (e.g. 16)
sdg: 11
# The SCSS color variable that matches the color of the SDG image 
color-variable: $color-sdg11
# The path to the SDG image
image: /assets/images/sdg/sdg11.svg
# The alt text for the SDG image
image-alt: 11 Sustainable Cities And Communities
targets:
    # The SDG target (e.g. 1, 2, or a, b, ...)
  - target: 1
    # The SDG target statement 
    statement: By 2030, ensure access for all to adequate, safe and affordable housing and basic services
  - target: 2
    statement: By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations, women, children, persons with disabilities and older persons
  - target: 3
    statement: By 2030, enhance inclusive and sustainable urbanization and capacity for participatory, integrated and sustainable human settlement planning and management in all countries
```

### Resources/Instructions
- [_data/internal/sdgs](https://github.com/hackforla/website/tree/gh-pages/_data/internal/sdgs)
- This issue is tracked in epic #4153
