### ISSUE TITLE
Creating a yml file for SDG 2

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4450]
### Overview
We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.

### Action Items
- [x] In `_data/internal/sdg`, add a file called `sdg2.yml`
- [x] In the file you just created, add the following:
```
# The Sustainable Development Goal (SDG) number (e.g. 16)
sdg: 2
# The SCSS color variable that matches the color of the SDG image 
color-variable: $color-sdg2
# The path to the SDG image
image: /assets/images/sdg/sdg2.svg
# The alt text for the SDG image
image-alt: 2 Zero Hunger
targets:
    # The SDG target (e.g. 1, 2, or a, b, ...)
  - target: 1
    # The SDG target statement 
    statement: By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round
```

### Resources/Instructions
- [_data/internal/sdgs](https://github.com/hackforla/website/tree/gh-pages/_data/internal/sdgs)
- This issue is tracked in epic #4153
