### ISSUE TITLE
Creating a yml file for SDG 3

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4451]
### Overview
We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.

### Action Items
- [x] In `_data/internal/sdg`, add a file called `sdg3.yml`
- [x] In the file you just created, add the following:
```
# The Sustainable Development Goal (SDG) number (e.g. 16)
sdg: 3
# The SCSS color variable that matches the color of the SDG image 
color-variable: $color-sdg3
# The path to the SDG image
image: /assets/images/sdg/sdg3.svg
# The alt text for the SDG image
image-alt: 3 Good Health And Well-being
targets:
    # The SDG target (e.g. 1, 2, or a, b, ...)
  - target: 4
    # The SDG target statement 
    statement: By 2030, reduce premature mortality from non-communicable diseases through prevention and treatment and promote mental health and well-being
```

### Resources/Instructions
- [_data/internal/sdgs](https://github.com/hackforla/website/tree/gh-pages/_data/internal/sdgs)
- This issue is tracked in epic #4153
