### ISSUE TITLE
Update Project Profile: ACCESS THE DATA

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/website#4939]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the project information for Access the Data so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find _projects/access-the-data.md file [^1] and make the following changes:
  - [x] Under the `leadership` section, 
    - [x] Remove
      ```
        - name: Bonnie Wolfe
          role: Agile Coach
          links:
            slack: 'https://hackforla.slack.com/team/UE1UG1YFP'
            github: 'https://github.com/experimentsinhonesty'
          picture: https://avatars.githubusercontent.com/experimentsinhonesty
      ```
    - [x] Remove
      ```
        - name: Leslie Luk
          role: UX Writer
          links:
            slack: 'https://hackforla.slack.com/team/U04960088CV'
            github: 'https://github.com/lesUXW'
          picture: https://avatars.githubusercontent.com/lesUXW
      ```
    - [x] Add 
      ```
        - name: Jason Yung
          role: Project Manager
          links:
            slack: 'https://hackforla.slack.com/team/U059W9P96C8'
            github: 'https://github.com/merlinsmagic'
          picture: https://avatars.githubusercontent.com/merlinsmagic
      ```
- [x] Using Docker, verify the changes by checking the Access the Data page [^2] in mobile, tablet, and desktop views

### Resources/Instructions
- Original request copied into this comment for future reference: https://github.com/hackforla/website/issues/4939#issuecomment-1639105125
[^1]: Directory to find the page once you have it in your IDE: `_projects/access-the-data.md`
[^2]: Project page URL: https://www.hackforla.org/projects/access-the-data
