### ISSUE TITLE
Update Project Profile:  Website Team

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4954]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Remove the following lines:
 ```
 - name: Brian Mui
    role: Merge Team
    links:
      slack: https://hackforla.slack.com/team/U04MFMMNJRH
      github: https://github.com/bootcamp-brian
    picture: https://avatars.githubusercontent.com/bootcamp-brian
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
