### ISSUE TITLE
Update Project Profile: Brigade Organizers Playbook

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5167]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Brigade Organizers Playbook project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observing the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/brigade-organizers-playbook.md` file: 
- [x] Find the `title:` variable and replace:
```
title: Brigade Organizers Playbook
```
with:
```
title: BOP
```
- [x] Find the `description:` variable and replace:
```
description: Each of the 80+ Code for America Brigades is an experiment which generates valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each others work, improving outcomes for the whole network.
```
with:
```
description: Each of the 80+ Code for America Brigades (chapters) was an experiment which generated valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each other's work, improving outcomes for the whole network.
``` 
- [x] Fnd the `leadership:` values and replace:
```
  - name: Bonnie Wolfe
    role: Agile Mentor & CfA National Advisory Council BOP project Co-Lead
    links:
      slack: 'https://codeforamerica.slack.com/team/UGREE50MT'
      github: 'https://github.com/experimentsinhonesty'
    picture: https://avatars.githubusercontent.com/experimentsinhonesty
  - name: Thad K.
    role: CfA National Advisory Council BOP project Co-Lead
    links:
      slack: 'https://codeforamerica.slack.com/team/UAU40G31A'
      github: 'https://github.com/thadk'
    picture: https://avatars.githubusercontent.com/thadk
  - name: Will Pfeffer
    role: CfA Brigade Network team representative
    links:
      slack: 'https://codeforamerica.slack.com/team/U014MEJV6KT'
      github: 'https://github.com/willpfeffer'
    picture: https://avatars.githubusercontent.com/willpfeffer
  - name: Sam H.
    role: Product Manager
    links:
      slack: 'https://codeforamerica.slack.com/team/U019C4LERSM'
      github: 'https://github.com/thesamwong'
    picture: https://avatars.githubusercontent.com/thesamwong
  - name: Serena Baleja
    role: Product Owner
    links:
      slack: 'https://codeforamerica.slack.com/team/U01FUJ7124S'
      github: 'https://github.com/Baleja'
    picture: https://avatars.githubusercontent.com/Baleja
  - name: Marianne Miranda
    role: UX Research Team Lead
    links:
      slack: 'https://codeforamerica.slack.com/team/U01ASEG8HK5'
      github: 'https://github.com/MarianneAnthonette'
    picture: https://avatars.githubusercontent.com/MarianneAnthonette
  - name: Raquel Nishijima
    role: Communication Designer & UX Researcher
    links:
      slack: 'https://codeforamerica.slack.com/team/U01EJ7KMLCV'
      github: 'https://github.com/raquelnish'
    picture: https://avatars.githubusercontent.com/raquelnish
  - name: Jon Kropko
    role: Data Scientist
    links:
      slack: 'https://codeforamerica.slack.com/team/UL9U380TH'
      github: 'https://github.com/jkropko'
    picture: https://avatars.githubusercontent.com/jkropko
  - name: Tan Zhou
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/UPMSC27G8'
      github: 'https://github.com/tan-zhou'
    picture: https://avatars.githubusercontent.com/tan-zhou
  - name: Helen Lin
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/U01B79J9V9B'
      github: 'https://github.com/osnickersnee'
    picture: https://avatars.githubusercontent.com/osnickersnee
  - name: Myranda Pierce
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/U01E521NT2L'
      github: 'https://github.com/myrandi'
    picture: https://avatars.githubusercontent.com/myrandi
  - name: Reem Mehdoui
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/U01DF6AE5TL'
      github: 'https://github.com/reemux'
    picture: https://avatars.githubusercontent.com/reemux
```
with:
```
  - name: Bonnie Wolfe
    role: BOP Project Lead
    links:
      slack: 'https://hackforla.slack.com/archives/C01Q24YF56J'
      github: 'https://github.com/experimentsinhonesty'
    picture: https://avatars.githubusercontent.com/experimentsinhonesty
  - name: Aleiya Gafar
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U01K7QMQ4TC'
      github: 'https://github.com/ag2463'
    picture: https://avatars.githubusercontent.com/ag2463
  - name: Evan Stalker
    role: Lead Designer
    links:
      slack: 'https://hackforla.slack.com/team/U04M979AY3G'
      github: 'https://github.com/ejstalker'
    picture: https://avatars.githubusercontent.com/ejstalker
  - name: Liz Brown
    role: UX Designer
    links:
      slack: 'https://hackforla.slack.com/team/U052DR4HVJS'
      github: 'https://github.com/ermbrown'
    picture: https://avatars.githubusercontent.com/ermbrown
  - name: Katrina Bonoan 
    role: UX Designer
    links:
      slack: 'https://hackforla.slack.com/team/U052LER0010'
      github: 'https://github.com/kit-katrina20'
    picture: https://avatars.githubusercontent.com/kit-katrina20
```
- [x] Replace the GitHub Link:

```
    url: 'https://github.com/codeforamerica/brigade-playbook'
```
with
```
    url: 'https://github.com/hackforla/BOP'
```
- [x] Replace the Slack Link:
```
    url: 'https://cfa.slack.com/archives/G0196272BBN'
```
with
```
    url: 'https://hackforla.slack.com/archives/C051M4JU562'
```
- [x] Verify the changes by viewing the [BOP](https://www.hackforla.org/projects/brigade-organizers-playbook) project page on your local environment in Docker and include a screenshot with your pull request

### Resources
- [brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
