### ISSUE TITLE
ER: Update Project Profile: ACCESS THE DATA 

### ISSUE THREAD

**Issue by wanyuguan** [hackforla/website#5274]
### Emergent Requirement - Problem
For ACCESS THE DATA project profile (https://www.hackforla.org/projects/access-the-data), move Jason Yung's listing under leadership to right after AJ Price so that product manager and project manager are displayed at the same location.

### Issue you discovered this emergent requirement in
- #4939 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [ ] NO

### Who was involved
@wanyuguan @Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
On the ACCESS THE DATA project profile page, users will not acknowledge intuitively that Jason Yung is the project manager for this project where they can reach out to learn more about the project. 

### Resources
Directory to find the page once you have it in your IDE: _projects/access-the-data.md [↩](https://github.com/hackforla/website/issues/4939#user-content-fnref-1-a5709c833bc0befa7a469f4c87c389e5)
Project page URL: https://www.hackforla.org/projects/access-the-data [↩](https://github.com/hackforla/website/issues/4939#user-content-fnref-2-a5709c833bc0befa7a469f4c87c389e5)
#4939 

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- [ ] Move Jason's listing under leadership to right after AJ
```
  - name: Jason Yung
    role: Project Manager
    links:
      slack: 'https://hackforla.slack.com/team/U059W9P96C8'
      github: 'https://github.com/merlinsmagic'
    picture: https://avatars.githubusercontent.com/merlinsmagic
```
