### ISSUE TITLE
Update Project Profile: Civic Tech Jobs (move Melinda Sukosd)

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5386]
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] **_MOVE only_** the entry for Melinda:
```
  - name: Melinda Sukosd
    role: UX Research Lead
    links:
      slack: https://hackforla.slack.com/team/U03T1G9F46P
      github: https://github.com/melkosm
    picture: https://avatars.githubusercontent.com/melkosm
```
 - [x] Move Melinda's profile immediately after any other Lead's profile
 - [x] Confirm on your local that links for the member appear to be correct (for the correct person) and are functioning
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252
