### ISSUE TITLE
Update Project Profile: LA TDM Calculator (remove Moji Momoh)

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5393]
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The LA TDM Calculator project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/tdm-calculator.md` file and find the `leadership` variable.
 - [x] **_Remove_** the entry:
```
  - name: Moji Momoh
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/D04HDM7DM18'
      github: 'https://github.com/mojimoh'
    picture: https://avatars.githubusercontent.com/mojimoh
```
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the LA TDM Calculator project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [LA TDM Calculator](https://www.hackforla.org/projects/tdm-calculator) project page
  - [tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)  
  - This issue was initiated by #5381
