### ISSUE TITLE
Update Project Profile: Guides Team (Remove Shawn Wong)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5584]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the project information for Guides Team so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find the `_projects/guides-team.md` file and make the following change:
  - [x] Under the `leadership` section, 
    - [x] Remove 
      ```
        - name: Shawn Wong
          role: Product Manager
          links:
            slack: 'https://hackforla.slack.com/team/U04MXRWPQ64'
            github: 'https://github.com/seannwvong'
          picture: https://avatars.githubusercontent.com/seannwvong
      ```
- [x] Verify the changes by viewing the Guides Team page [^1] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
- This issue was initiated by #5407
[^1]: Project page URL: https://www.hackforla.org/projects/guides-team
