### ISSUE TITLE
Update Project Profile: Guides Team (Add Rhoda Michael)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5623]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

#### Developer
- [ ] In your IDE, open the `_projects/guides-team.md` file
- [ ] Observe the existing syntax of the front matter block [^1] in the file
- [ ] Find the `leadership` variable and make the following change:
  - [ ] Add the following as a new entry
    ```
      - name: Rhoda Michael
        github-handle: the-techgurl
        role: UX Research Lead
        links:
          slack: 'https://hackforla.slack.com/team/U05JS9NLNQJ'
          github: 'https://github.com/the-techgurl'
        picture: https://avatars.githubusercontent.com/the-techgurl
    ```
- [ ] Verify the changes by viewing the Guides Team page [^2] in your local environment and include before and after screenshots with your pull request
- [ ] Once your pull request is merged, go to #5407 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5407 to **Questions / In Review** column and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #5407
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/guides-team
