### ISSUE TITLE
Update Project Profile: Guides Team (Add Sarah Levine)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5624]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and make the following change:
  - [x] Add the following as a new entry
    ```
      - name: Sarah Levine
        role: Product Manager
        links:
          slack: 'https://hackforla.slack.com/team/U05RWQJ8YKU'
          github: 'https://github.com/levines2017'
        picture: https://avatars.githubusercontent.com/levines2017
    ```
  - [x] Place this profile with the other Product Manager profile(s)
- [x] Verify the changes by viewing the Guides Team page [^2] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
- This issue was initiated by #5407
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/guides-team
