### ISSUE TITLE
Update Project Profile: Expunge Assist (Add Sydney Walcoff)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5760]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Sydney Walcoff
    github-handle: sydneywalcoff
    role: Development, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U02P0A49XL4
      github: https://github.com/sydneywalcoff
    picture: https://avatars.githubusercontent.com/sydneywalcoff
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
      <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
      <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
    </details>

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist
