### ISSUE TITLE
Update Project Profile: Lucky Parking (Add Danny Pham)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5792]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Danny Pham
    github-handle: dannycpham
    role: Product Manager Lead
    links:
      slack: https://hackforla.slack.com/team/U041DP398GH
      github: https://github.com/dannycpham
    picture: https://avatars.githubusercontent.com/dannycpham
```
- [x] If there are other Product Manager Leads, place this profile after the other Product Manager Leads' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column, add a **ready for dev lead** label to it, and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
