### ISSUE TITLE
Update Project Profile: 311 Data (Update Technologies, Add Ahmed Awadalla & Edwin Jue)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5854]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/311-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `technologies` variable and change the following:

**From:**
```
technologies:
  - React
  - Redux
  - Material-UI
  - Mapbox
  - AWS
  - FastAPI
  - Redis
  - PostgreSQL
  - Prefect
  - Docker
  - Figma
  - Adobe CC
  - Miro
```
**To:**
```
technologies:
  - React
  - Redux
  - Material-UI
  - DuckDb
  - HuggingFace
  - GitHub Pages
  - Mapbox
```
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Ahmed Awadalla
    github-handle: ahmedsalah0130
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05Q80JEGG4
      github: https://github.com/ahmedsalah0130
    picture: https://avatars.githubusercontent.com/ahmedsalah0130
```
- [x] If there are other Product Managers, place Ahmed's profile after the other Product Managers' profiles
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Edwin Jue
    github-handle: edwinjue
    role: Engineering Lead
    links:
      slack: https://hackforla.slack.com/team/U03SUUZMFEV
      github: https://github.com/edwinjue
    picture: https://avatars.githubusercontent.com/edwinjue
```
- [x] If there are other Engineering Leads, place Edwin's profile after the other Engineering Leads' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] 311 Data page [^2]
  - [x] the project's card on the Projects' page [^3]
- [x] Once your pull request is merged, go to #5786 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5786 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #5786 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/311-data
[^3]: Projects page URL: https://www.hackforla.org/projects/
