### ISSUE TITLE
Edits and additions to "Project Profile Card" template

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5857]
### Overview
There are some projects at Hack for LA that need to be added to the website. We want to update our `project-profile-card-review-and-update.yml` file to provide options for adding a new project card that will be displayed on the website.

### Action Items
Refer to the `project-card-review-and-update.yml` file. In this file:
- [x] Replace the line:
```
description: "To track project profile card updates"
```
with:
```
description: "To track project profile card updates or add a new project profile card"
```
- [x] Locate the code for the dropdown list labelled "Project Name". At the start of the list near line 18, add:
```
- "---New Project---"
```
- [x] Locate the code for the dropdown list labelled "Project Card URL". At the start of the list near line 62, add:
```
- "---New Project---"
```
- [x] Locate the code for the dropdown labelled "Update the Description?". **_After_** this section, add the following new section. Provide a single line space both above and below:
```
  - type: dropdown
    id: update-hero-image-yes-no
    attributes:
      label: Update the Hero Image?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: hero-image
    attributes:
      label: Hero Image
```
- [x]  Currently, there are three lines after the dropdown labelled "Update the Image?". Change this to a single line for consistency with the rest of the file.
- [x] Locate the code for the dropdown labelled "Update the Image?". After `validations:` `required: true`, replace:
```
  - type: input
```
with:
```
  - type: textarea
```
- [x] Locate the code for the dropdown labelled "Update the Technologies?". Replace the line:
```
      label: Technologies (maximum 26 characters)
```
with:
```
      label: Technologies (maximum 26 characters per technology name)
```
- [x] Change the spacing both after this line and after the dropdown labelled "Update the Partner(s)", each to a single line.

### Resources/Instructions
- [project-card-review-and-update.yml](.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml)

This issue was initiated by ER #4901
