### ISSUE TITLE
Update Project Profile: 311 Data (Remove Michael Criste, Add Ryan Chase & Anna Kim)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5860]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/311-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Michael Criste
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U048U430FQV'
      github: 'https://github.com/mc759'
    picture: https://avatars.githubusercontent.com/mc759
```
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Ryan Chase
    github-handle: ryanfchase
    role: Project Manager, Developer
    links:
      slack: https://hackforla.slack.com/team/U052L9R6ETD
      github: https://github.com/ryanfchase
    picture: https://avatars.githubusercontent.com/ryanfchase
```
- [x] If there are other Project Managers, place Ryan Chase's profile after the other Project Managers' profiles
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Anna Kim
    github-handle: annaseulgi
    role: UX Design Lead, Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05JKGV3F4N
      github: https://github.com/annaseulgi
    picture: https://avatars.githubusercontent.com/annaseulgi
```
- [x] If there are other Product Managers, place Anna Kim's profile after the other Product Managers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] 311 Data page [^2]
- [x] Once your pull request is merged, go to #5786 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #5786 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #5786
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/311-data
