### ISSUE TITLE
Update Communities of Practice: UI/UX (Add Peter Gwon)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5874]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep communities of practice information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/ui-ux.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Peter Gwon
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U051F68PG2C
      github: https://github.com/pogwon
    picture: https://avatars.githubusercontent.com/pogwon
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the UI/UX section on the Communities of Practice page [^2]
- [x] Once your pull request is merged, go to #5824 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] Move #5824 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #5824
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice
