### ISSUE TITLE
Update Project Profile: Expunge Assist (Add Mireya V. Aviles)

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5919]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Mireya V. Aviles
    github-handle: vanessaavviles
    role: Product Manager, Design
    links:
      slack: https://hackforla.slack.com/team/U0429M52LTY
      github: https://github.com/vanessaavviles
    picture: https://avatars.githubusercontent.com/vanessaavviles
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
- This issue was initiated by talking directly with the stakeholder
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist
