### ISSUE TITLE
Remove Code for America logo and references in partners.yml and sponsors.yml

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5960]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to remove references to the Code for America logo from the Partners and Sponsors markdown, and delete the graphic file.  

### Action Items
- [x] In your local IDE, navigate to `_data/internal/partners.yml`
- [x] Remove these lines:
 ```
- name: Code for America
  image: /assets/images/sponsors/code-for-america.svg
  link: https://www.codeforamerica.org/
  program-area:
    - Vote / Representation
``` 
- [x] In your local IDE, navigate to `_data/internal/sponsors.yml`
- [x] Remove these lines:
 ```
- name: Code for America
  link: https://www.codeforamerica.org/
  img_url: /assets/images/sponsors/code-for-america.svg
  position: 
``` 
- [x] Using Docker, confirm that the Code for America logo no longer appears on the "Partners" section of the "About Us" page

### Resources/Instructions
1. "Partners" section of the "About Us" webpage: https://www.hackforla.org/about/#partners
2. This issue was created from #5953`
