### ISSUE TITLE
Update Project Profile: Access the Data (Remove Aparna Gopal, Judson Lester, Tony Delgado Willis)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6065]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/access-the-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Judson Lester
    role: Developer
    links:
      slack: 'https://hackforla.slack.com/team/U9NFW84QK'
      github: 'https://github.com/nyarly'
    picture: https://avatars.githubusercontent.com/nyarly
  - name: Aparna Gopal
    role: UX Researcher
    links:
      slack: 'https://hackforla.slack.com/team/U0245UJP868'
      github: 'https://github.com/Aparna1Gopal'
    picture: https://avatars.githubusercontent.com/Aparna1Gopal
  - name: Tony Delgado
    github-handle: 
    role: Developer
    links:
      slack: 'https://hackforla.slack.com/team/U05422GPUQ2'
      github: 'https://github.com/TonyDelgadoWillis'
    picture: https://avatars.githubusercontent.com/TonyDelgadoWillis
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Access the Data page [^2]
- [x] Once your pull request is merged, go to #6018 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6018 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6018
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/access-the-data
