### ISSUE TITLE
Update civic tech index project card

### ISSUE THREAD

**Issue by arunprakash87** [hackforla/website#607]
### Overview
New Product manager and would like to update their information.

### Action Items
Change from 
```
#  - name: Marissa Wilson
#   role: Product Manager
#   links:
#     slack: 'https://app.slack.com/team/UUG26TUTB'
#     github: 'https://github.com/mw376707'
#   picture: https://avatars.githubusercontent.com/mw376707
```
to
```
   - name: Arun Prakash
    role: Product Manager
    links:
       slack: 'https://app.slack.com/team/U015GPCKUFK'
       github: 'https://github.com/arunprakash87'
      picture: https://avatars.githubusercontent.com/arunprakash87
```
