### ISSUE TITLE
Update Project Profile: Expunge Assist (Reorder leadership members)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6078]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to reorder the way the leadership team members are displayed on the Expunge Assist page so that members with the same role are grouped together and it looks more organized.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, we will be changing the order of the profiles so the result is this order:
  - Analicia Mejia Mesinas
  - Lane Mitchell
  - Curtis Barber
  - Mireya V. Aviles
  - Sydney Walcoff
  - Anita Morales
  - Justin Yeh
  - Samantha Hyler

So, change

**From:**
```
  - name: Analicia Mejia Mesinas
    github-handle: amejiamesinas
    role: Product Manager, UX Research
    links:
      slack: https://hackforla.slack.com/team/U04J34E73CG
      github: https://github.com/amejiamesinas
    picture: https://avatars.githubusercontent.com/amejiamesinas
  - name: Samantha Hyler
    github-handle: SamHyler
    role:  UX Content, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U025XR6MY6S
      github: https://github.com/SamHyler
    picture: https://avatars.githubusercontent.com/SamHyler
  - name: Lane Mitchell
    github-handle: lmitch10
    role: Product Manager, Development
    links:
      slack: https://hackforla.slack.com/team/U052LEP0BSN
      github: https://github.com/lmitch10
    picture: https://avatars.githubusercontent.com/lmitch10
  - name: Justin Yeh
    github-handle: jyehllow
    role: UX Design, Team Co-lead
    links:
      slack: https://hackforla.slack.com/team/U03PNBDLXL1
      github: https://github.com/jyehllow
    picture: https://avatars.githubusercontent.com/jyehllow
  - name: Anita Morales
    github-handle: anitadesigns
    role: UX Design, Team Co-lead
    links:
      slack: https://hackforla.slack.com/team/U03F43PFR3K
      github: https://github.com/anitadesigns
    picture: https://avatars.githubusercontent.com/anitadesigns
  - name: Curtis Barber
    github-handle: CBx3000
    role: Product Manager, Content
    links:
      slack: https://hackforla.slack.com/team/U05RZAETCQ4
      github: https://github.com/CBx3000
    picture: https://avatars.githubusercontent.com/CBx3000
  - name: Sydney Walcoff
    github-handle: sydneywalcoff
    role: Development, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U02P0A49XL4
      github: https://github.com/sydneywalcoff
    picture: https://avatars.githubusercontent.com/sydneywalcoff
  - name: Mireya V. Aviles
    github-handle: vanessaavviles
    role: Product Manager, Design
    links:
      slack: https://hackforla.slack.com/team/U0429M52LTY
      github: https://github.com/vanessaavviles
    picture: https://avatars.githubusercontent.com/vanessaavviles
```

**To:**
```
  - name: Analicia Mejia Mesinas
    github-handle: amejiamesinas
    role: Product Manager, UX Research
    links:
      slack: https://hackforla.slack.com/team/U04J34E73CG
      github: https://github.com/amejiamesinas
    picture: https://avatars.githubusercontent.com/amejiamesinas
  - name: Lane Mitchell
    github-handle: lmitch10
    role: Product Manager, Development
    links:
      slack: https://hackforla.slack.com/team/U052LEP0BSN
      github: https://github.com/lmitch10
    picture: https://avatars.githubusercontent.com/lmitch10
  - name: Curtis Barber
    github-handle: CBx3000
    role: Product Manager, Content
    links:
      slack: https://hackforla.slack.com/team/U05RZAETCQ4
      github: https://github.com/CBx3000
    picture: https://avatars.githubusercontent.com/CBx3000
  - name: Mireya V. Aviles
    github-handle: vanessaavviles
    role: Product Manager, Design
    links:
      slack: https://hackforla.slack.com/team/U0429M52LTY
      github: https://github.com/vanessaavviles
    picture: https://avatars.githubusercontent.com/vanessaavviles 
  - name: Sydney Walcoff
    github-handle: sydneywalcoff
    role: Development, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U02P0A49XL4
      github: https://github.com/sydneywalcoff
    picture: https://avatars.githubusercontent.com/sydneywalcoff
  - name: Anita Morales
    github-handle: anitadesigns
    role: UX Design, Team Co-lead
    links:
      slack: https://hackforla.slack.com/team/U03F43PFR3K
      github: https://github.com/anitadesigns
    picture: https://avatars.githubusercontent.com/anitadesigns
  - name: Justin Yeh
    github-handle: jyehllow
    role: UX Design, Team Co-lead
    links:
      slack: https://hackforla.slack.com/team/U03PNBDLXL1
      github: https://github.com/jyehllow
    picture: https://avatars.githubusercontent.com/jyehllow
  - name: Samantha Hyler
    github-handle: SamHyler
    role:  UX Content, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U025XR6MY6S
      github: https://github.com/SamHyler
    picture: https://avatars.githubusercontent.com/SamHyler
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist
