### ISSUE TITLE
Creating a yml file for SDG 13

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6221]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.

### Action Items
- [ ] In `_data/internal/sdg`, add a file called `sdg13.yml`
- [ ] In the file you just created, add the following:
```
# The Sustainable Development Goal (SDG) number (e.g. 16)
sdg: 13
# The SCSS color variable that matches the color of the SDG image 
color-variable: $color-sdg13
# The path to the SDG image
image: /assets/images/sdg/sdg13.svg
# The alt text for the SDG image
image-alt: 13 Climate Action
targets:
    # The SDG target (e.g. 1, 2, or a, b, ...)
  - target: 3
    # The SDG target statement 
    statement: Improve education, awareness-raising and human and institutional capacity on climate change mitigation, adaptation, impact reduction and early warning
```

### Resources/Instructions
- [_data/internal/sdgs](https://github.com/hackforla/website/tree/gh-pages/_data/internal/sdgs)
- This issue is tracked in epic #4153
