### ISSUE TITLE
Update Project Profile: Food Oasis (Add Andy Arensman, Belen Garcia Martinez, June Zhao)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6310]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/food-oasis.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as new entries:
```
  - name: Andy Arensman
    github-handle: andyarensman
    role: Full Stack Engineer
    links:
      slack: https://hackforla.slack.com/team/U04PFGPR19Q
      github: https://github.com/andyarensman
    picture: https://avatars.githubusercontent.com/andyarensman
  - name: Belen Garcia Martinez
    github-handle: 93Belen
    role: Full Stack Engineer
    links:
      slack: https://hackforla.slack.com/team/U056TQ9UA3C
      github: https://github.com/93Belen
    picture: https://avatars.githubusercontent.com/93Belen
  - name: June Zhao
    github-handle: junjun107
    role: Full Stack Engineer
    links:
      slack: https://hackforla.slack.com/team/U03UWG0EP7V
      github: https://github.com/junjun107
    picture: https://avatars.githubusercontent.com/junjun107
```
- [x] If there are other Full Stack Engineers, place Andy's, Belen's, and June's profiles after the other Full Stack Engineers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Food Oasis page [^2]
- [x] Once your pull request is merged, go to #6285  and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6285 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6285 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/food-oasis
