### ISSUE TITLE
Update Project Profile: Food Oasis (Add Krista Strucke, Qiqi Zheng, Saumil Dhankar)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6311]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/food-oasis.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as new entries:
```
  - name: Krista Strucke
    github-handle: kurikurichan
    role: Full Stack Engineer
    links:
      slack: https://hackforla.slack.com/team/U04PHV2HUF6
      github: https://github.com/kurikurichan
    picture: https://avatars.githubusercontent.com/kurikurichan
  - name: Qiqi Zheng
    github-handle: qiqicodes
    role: Full Stack Engineer
    links:
      slack: https://hackforla.slack.com/team/U01LM6SE70A
      github: https://github.com/qiqicodes
    picture: https://avatars.githubusercontent.com/qiqicodes
  - name: Saumil Dhankar
    github-handle: saumildhankar
    role: Full Stack Engineer
    links:
      slack: https://hackforla.slack.com/team/U02AG2K2BB3
      github: https://github.com/saumildhankar
    picture: https://avatars.githubusercontent.com/saumildhankar
```
- [x] If there are other Full Stack Engineers, place Krista's, Qiqi's, and Saumil's profiles after the other Full Stack Engineers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Food Oasis page [^2]
- [ ] Once your pull request is merged, go to #6285  and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6285 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6285 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/food-oasis
