### ISSUE TITLE
Update Project Profile: Food Oasis (Remove Seiko Igi, Stacey Rebekah Scott, Erin Dean)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6312]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/food-oasis.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
  - [x] 
    ```
      - name: Seiko Igi
        role: Senior Product Designer
        links:
          slack: "https://hackforla.slack.com/team/U02U55MQEQ7"
          github: "https://github.com/sei1122"
        picture: https://avatars.githubusercontent.com/sei1122
    ```
  - [x] 
    ```
      - name: Stacey Rebekah Scott
        role: Senior Project Manager
        links:
          slack: "https://hackforla.slack.com/team/U02U9Q5DUF6"
          github: "https://github.com/staceyrebekahscott"
        picture: https://avatars.githubusercontent.com/staceyrebekahscott
    ```
  - [x] 
    ```
      - name: Erin Dean
        role: Senior Product Manager
        links:
          slack: "https://hackforla.slack.com/team/U03JSNJ3UKE"
          github: "https://github.com/itserindean"
        picture: https://avatars.githubusercontent.com/itserindean
    ```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Food Oasis page [^2]
- [x] Once your pull request is merged, go to #6285  and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6285 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6285 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/food-oasis
