### ISSUE TITLE
Update Project Profile: Food Oasis (Reorder leadership member)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6313]
### Dependency
- [x] #6317 

### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to reorder the way the leadership team members are displayed on the Food Oasis page so that members with the same role are grouped together and it looks more organized.

### Action Items
- [x] In your IDE, open the `_projects/food-oasis.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, find Hannah Zulueta's profile information.
- [x] Then, move Hannah Zulueta's profile information so it is after John Darragh's profile information. The resultant code should be:
```
leadership:
  - name: John Darragh
    role: Lead Developer
    links:
      slack: "https://hackforla.slack.com/team/UFLDX9V19"
      github: "https://github.com/entrotech"
    picture: https://avatars.githubusercontent.com/entrotech
  - name: Hannah Zulueta
    role: Lead Developer
    links:
      slack: "https://hackforla.slack.com/team/U9SCMTNK0"
      github: "https://github.com/hanapotski"
    picture: https://avatars.githubusercontent.com/hanapotski
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Food Oasis page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/food-oasis
