### ISSUE TITLE
Update Project Profile: Guides Team (Remove Sarah Levine, Add Ayma Rahman)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6373]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Sarah Levine
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U05RWQJ8YKU'
      github: 'https://github.com/levines2017'
    picture: https://avatars.githubusercontent.com/levines2017
```
- [x] Find the `leadership` variable and add the following:
```
  - name: Ayma Rahman
    github-handle: aymarmsba
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U06C183Q2HL
      github: https://github.com/aymarmsba
    picture: https://avatars.githubusercontent.com/aymarmsba
```
- [x] If there are other Product Managers, place Ayma's profile after the other Product Managers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Guides Team page [^2]
- [ ] Once your pull request is merged, go to #6364 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6364 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6364 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/guides-team
