### ISSUE TITLE
Add Atwater Village Logo to Citizen Engagement page

### ISSUE THREAD

**Issue by A-Wu5** [hackforla/website#6474]
### Overview
We need to add the logo for Atwater Village to the Citizen Engagement page so that we accurately represent the relationships the projects have.

### Action Items

- [x] Navigate to `_data/internal/sdg/partners.yml` in your IDE
- [x] Insert the following snippet to the file after "Los Angeles Department of Neighborhood Empowerment", that is after line 5:
```
- name: Atwater Village
  image: /assets/images/partners/atwater-village.png
  link: https://www.atwatervillage.org/
  program-area:
    - Citizen Engagement
```
- [x] Upload the Atwater Village logo to `/assets/images/partners` as `atwater-village.png`
- [x] Verify the changes by viewing the `Citizen Engagement` page in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
1. Atwater Village logo
![ATWATER VILLAGE 1](https://github.com/hackforla/website/assets/37763229/4ff4ecb3-99ad-450f-8c53-e8ef52818414)
2. [Citizen Engagement Page](https://www.hackforla.org/citizen-engagement)

This issue initiated by ER #5098
