### ISSUE TITLE
ER: Update Project Profile: Expunge Assist

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/website#6475]
### Dependency
- [x] #6510 

### Project Name

Expunge Assist

### Project Card URL

expunge-assist.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Lane Mitchell

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Sylvia Nam
GitHub Handle: sylvia-nam
Role: UX Research, Team Lead
Slack Member ID: U06E9RQ8DRA

- [x] Keep the current card as is for Mireya per this comment : https://github.com/hackforla/website/issues/6475#issuecomment-2025896976 
~Name: Mireya Aviles
GitHub Handle: vanessaavviles
Role: UX Design, Product Manager 
Slack Member ID: U0429M52LTY~

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
## Issue Writing

### Initial
- **Availability:** 1.5 hour
- **ETA:** Saturday, March 23, 2024

### Progress Update on Sunday, March 24, 2024
- **Progress:** Wrote issue #6510
- **Blockers:** Awaiting response from https://github.com/hackforla/website/issues/6475#issuecomment-2016738431
- **Availability:** TBD; dependent on answer to blocker
- **ETA:** TBD; dependent on answer to blocker

**Comment by JessicaLucindaCheng** [comment]
```
  - name: Mireya V. Aviles
    github-handle: vanessaavviles
    role: Product Manager, Design
    links:
      slack: https://hackforla.slack.com/team/U0429M52LTY
      github: https://github.com/vanessaavviles
    picture: https://avatars.githubusercontent.com/vanessaavviles 
```

Name: Mireya Aviles
GitHub Handle: vanessaavviles
Role: UX Design, Product Manager
Slack Member ID: U0429M52LTY

Mireya is already on the [Expunge Assist](https://www.hackforla.org/projects/expunge-assist) page:
<img width="297" alt="Current profile for Mireya on the Expunge Assist page." src="https://github.com/hackforla/website/assets/31293603/67c8fca9-6c07-4f86-ba05-f4476ebf9586">
