### ISSUE TITLE
Update Project Profile: Guides Team (Add Mary Gabrielian)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6509]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following:
```
  - name: Mary Gabrielian
    github-handle: marygabrielian
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U06KMNL8ETY
      github: https://github.com/marygabrielian
    picture: https://avatars.githubusercontent.com/marygabrielian
```
- [x] If there are other Product Managers, place Mary Gabrielian's profile after the other Product Managers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Guides Team page [^2]
- [x] Once your pull request is merged, go to #6466 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6466 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6466 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/guides-team
