### ISSUE TITLE
Update Project Profile: Expunge Assist (Remove Lane Mitchell, Add Sylvia Nam)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6510]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Lane Mitchell
    github-handle: lmitch10
    role: Product Manager, Development
    links:
      slack: https://hackforla.slack.com/team/U052LEP0BSN
      github: https://github.com/lmitch10
    picture: https://avatars.githubusercontent.com/lmitch10
```
- [x] Find the `leadership` variable and add the following:
```
  - name: Sylvia Nam
    github-handle: sylvia-nam
    role: UX Research, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U06E9RQ8DRA
      github: https://github.com/sylvia-nam
    picture: https://avatars.githubusercontent.com/sylvia-nam
```
- [x] If there are other Team Leads, place Sylvia Nam's profile after the other Team Leads' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Expunge Assist page [^2]
- [ ] Once your pull request is merged, go to #6475 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6475 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6475
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/expunge-assist
