### ISSUE TITLE
Update Project Profile: Civic Tech Jobs (Remove Salima Yacoubi Soussane & Sabrina Heasley; Add Kanika Chotani)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6636]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `_projects/civic-tech-jobs.md` file
- [ ] Observe the existing syntax of the front matter block [^1] in the file
- [ ] Find the `leadership` variable and do the following:
  - [ ] Remove
  ```
    - name: Salima Yacoubi Soussane 
      github-handle:
      role: Product Manager
      links:
        slack: https://hackforla.slack.com/team/U03HUJM7YCX
        github: https://github.com/Salimays
      picture: https://avatars.githubusercontent.com/Salimays
  ```
  - [ ] Remove
  ```
    - name: Sabrina Heasley 
      github-handle: 
      role: Product Manager
      links:
        slack: https://hackforla.slack.com/team/U05GDBDPEDR
        github: https://github.com/sabheasley
      picture: https://avatars.githubusercontent.com/sabheasley
  ```
  - [ ] Add the following:
  ```
    - name: Kanika Chotani
      github-handle: kchotani
      role: Product Manager
      links:
        slack: https://hackforla.slack.com/team/U02E7ATACAV
        github: https://github.com/kchotani
      picture: https://avatars.githubusercontent.com/kchotani
  ```
    - [ ] If there are other Product Managers, place Kanika Chotani's profile after the other Product Managers' profiles
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] Civic Tech Jobs page [^2]
- [ ] Once your pull request is merged, go to #6583 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6583 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6583
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
