### ISSUE TITLE
Update Project Profile: Civic Tech Jobs (Remove Jen Chung, Melinda Sukosd, & Jenn Wu; Update Lu Feng)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6638]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the **leadership** variable and do the following:
  - [x] Remove
    ```
      - name: Jen Chung 
        github-handle: 
        role: UX/UI Design Lead
        links:
          slack: https://hackforla.slack.com/team/U02A6H5PVAA
          github: https://github.com/jenchuu
        picture: https://avatars.githubusercontent.com/jenchuu
    ```
  - [x] Remove
    ```
      - name: Melinda Sukosd
        role: UX Research Lead
        links:
          slack: https://hackforla.slack.com/team/U03T1G9F46P
          github: https://github.com/melkosm
        picture: https://avatars.githubusercontent.com/melkosm
    ```
  - [x] Remove
    ```
      - name: Jenn Wu
        github-handle:
        role: UX Researcher Lead
        links:
          slack: https://hackforla.slack.com/team/U05JS3V38TV
          github: https://github.com/jayywu
        picture: https://avatars.githubusercontent.com/jayywu 
    ```
  - [x] Find Lu Feng's profile:
    ```
      - name: Lu Feng
        github-handle:
        role: UX/UI Designer
        links:
          slack: https://hackforla.slack.com/team/U03NV47TG4X
          github: https://github.com/fenglugithub
        picture: https://avatars.githubusercontent.com/fenglugithub
    ```
    - [x] Move Lu's profile so it is after the other Product Managers' and Leads' profiles
    - [x] Update the profile by adding the GitHub handle `fenglugithub` to the **github-handle** variable and change the **role** to `UI/UX Lead` so the result is
      ```
        - name: Lu Feng
          github-handle: fenglugithub
          role: UI/UX Lead
          links:
            slack: https://hackforla.slack.com/team/U03NV47TG4X
            github: https://github.com/fenglugithub
          picture: https://avatars.githubusercontent.com/fenglugithub
      ```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [x] Once your pull request is merged, go to #6583 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6583 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6583
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs

**Comment by jonnyoe** [comment]
Availability: Friday 8:30-11pm, Saturday 7pm-11pm, Sunday 3pm-5pm, Monday 2pm-6pm
ETA: By Tuesday 12/23

**Comment by ExperimentsInHonesty** [comment]
@jono4727 I will move your issue to the in progress column.  In the future, please do that on any new issues you self assign or get assigned to.

**Comment by jonnyoe** [comment]
Will need one more day to do this. Apologies still getting acquainted with git/github

**Comment by freaky4wrld** [comment]
Hey @Jessica Cheng (she/her) I was curious why did we use `github-handle: fenglugithub` here , besides all other profiles follow `github-handle:` should it be like this, should we update the template

``` yaml
 - name: Lu Feng
    github-handle: 
    role: UI/UX Lead
    links:
      slack: https://hackforla.slack.com/team/U03NV47TG4X
      github: https://github.com/fenglugithub
    picture: https://avatars.githubusercontent.com/fenglugithub
```

I was reviewing https://github.com/hackforla/website/pull/6748 and found the above conflict, just wanted to confirm this from you.
