### ISSUE TITLE
Update Project Profile: Civic Tech Jobs (Remove Tin Wei Chung; Add Armon Brown & Carmen Mak)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6639]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and remove the following:
  ```
    - name: Tin Wei Chung
      github-handle:
      role: UX/UI Designer
      links:
        slack: https://hackforla.slack.com/team/U03P6Q6FSQ5
        github: https://github.com/TCUX
      picture: https://avatars.githubusercontent.com/TCUX
  ```
- [x] For the `leadership` variable, add the following profiles. If there are other UX/UI Designers, place Armon Brown's and Carmen Mak's profile after the other UX/UI Designers' profiles
  - [x] Add
    ```
      - name: Armon Brown
        github-handle: stanarmon
        role: UX/UI Designer
        links:
          slack: https://hackforla.slack.com/team/U06J0UCAWHE
          github: https://github.com/stanarmon
        picture: https://avatars.githubusercontent.com/stanarmon
    ```
  - [x] Add
    ```
      - name: Carmen Mak
        github-handle: CarmenMM1
        role: UX/UI Designer
        links:
          slack: https://hackforla.slack.com/team/U06313EMD41
          github: https://github.com/CarmenMM1
        picture: https://avatars.githubusercontent.com/CarmenMM1
    ```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [ ] Once your pull request is merged, go to #6583 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6583 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6583
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
