### ISSUE TITLE
Update Project Profile: Civic Tech Jobs (Remove Gabriel Vicencio & Nga Do; Add Brenda Njemanze & Manju Chawla)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6640]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and remove the following:
  - [x] Remove 
    ```
      - name: Gabriel Vicencio
        github-handle:
        role: UX/UI Designer
        links:
          slack: https://hackforla.slack.com/team/U03P33ZNPGW
          github: https://github.com/geibu
        picture: https://avatars.githubusercontent.com/geibu
    ``` 
  - [x] Remove 
    ```
      - name: Nga Do
        github-handle:
        role: UX Researcher
        links:
          slack: https://hackforla.slack.com/team/U05JS3BS9FD
          github: https://github.com/ngadoq
        picture: https://avatars.githubusercontent.com/ngadoq 
    ``` 
- [x] For the `leadership` variable, add the following profiles.
  - [x] Add Brenda Njemanze's profile. If there are other UX/UI Designers, place Brenda Njemanze's profile after the other UX/UI Designers' profiles.
    ```
      - name: Brenda Njemanze
        github-handle: brendasdesign
        role: UX/UI Designer
        links:
          slack: https://hackforla.slack.com/team/U06MWMRSCJW
          github: https://github.com/brendasdesign
        picture: https://avatars.githubusercontent.com/brendasdesign
    ```
  - [x] Add Manju Chawla's profile. If there are other UX Researchers, place Manju Chawla's profile after the other UX Researchers' profiles.
    ```
      - name: Manju Chawla
        github-handle: itsmanjuchawla
        role: UX Researcher
        links:
          slack: https://hackforla.slack.com/team/U06E9T37H9A
          github: https://github.com/itsmanjuchawla
        picture: https://avatars.githubusercontent.com/itsmanjuchawla
    ```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [x] Once your pull request is merged, go to #6583 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6583 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6583
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
