### ISSUE TITLE
Add GitHub token / permissions for `stefanzweifel/git-auto-commit-action`

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6843]
### Overview
The `schedule-monthly.yml` workflow from earlier this month was not successful. After review, the cause has been traced to insufficient permissions given to the "stefanzweifel/git-auto-commit-action" that conflicts with the `hackforla/website`'s Branch Protection Rules. A fix is needed.

### Details
Two other HfLA workflows use the same auto-commit action, and both run without errors. The `schedule-monthly.yml` automation's failure can be traced back to the workflow's insufficient permissions to bypass the Branch Protection Rules. The following Action Items were tested in a personal repo and appear to address the problem.  

Additionally, this issue corrects a minor error in a comment, and removes the manual trigger `workflow dispatch:` since we do not want this action to be triggered off-schedule. 

### Action Items

Refer to [schedule-monthly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly.yml). 
- [x] On Line 3, replace `3:00 PDT` with the correct time of `4:00 PDT`
- [x] Remove the entirety of Line 7, `workflow-dispatch:`  
- [x] At lines 15-17, replace:  
  ```
    # Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4
  ```  
  with:  
  ```  
    # Checkout repo, and provide authorization token for `stefanzweifel/git-auto-commit-action` below
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        token: ${{ secrets.HACKFORLA_ADMIN_TOKEN }}
  ```  
- [x] Although this workflow affects a GitHub Action, the GHA itself does not require testing (it has been fully tested by previous issues)

### Resources/Instructions
- [stefanzweifel/git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action) documentation
- [specific section regarding tokens](https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs)
