### ISSUE TITLE
Update Project Profile: Expunge Assist (Remove Curtis Barber, Add Maria Weissman)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6866]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and
  - [x] Remove the following:
  ```
    - name: Curtis Barber
      github-handle: CBx3000
      role: Product Manager, Content
      links:
        slack: https://hackforla.slack.com/team/U05RZAETCQ4
        github: https://github.com/CBx3000
      picture: https://avatars.githubusercontent.com/CBx3000
  ```
  - [x] Add the following profile. If there are other Product Managers, place Maria Weissman's profile before the other Product Managers' profiles.
  ```
    - name: Maria Weissman
      github-handle: mariaweissman
      role: Product Manager, Project Manager
      links:
        slack: https://hackforla.slack.com/team/U06REA9H3FF
        github: https://github.com/mariaweissman
      picture: https://avatars.githubusercontent.com/mariaweissman
  ```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Expunge Assist page [^2]
- [x] Once your pull request is merged, go to #6834 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6834 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #6834
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/expunge-assist
