### ISSUE TITLE
Create workflow to comment on PR if dev doesn't link issue 

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7140]
### Overview
Often, a developer will neglect to reference the issue that they worked on when creating a PR, which affects other workflows. If this is the case, we want a workflow to comment on the PR so that the developer will provide the correct link.
 
### Action Items
- [x] In [pull-request-trigger.yml](https://github.com/hackforla/website/edit/gh-pages/.github/workflows/pull-request-trigger.yml) replace the 'placeholder' job:  
  ```  
   # Placeholder action: Delete when new jobs added 
  Hello-World:
    runs-on: ubuntu-latest
    steps:
     - run: echo "🍺 This job was automatically triggered by a ${{ github.event_name }} event."
  ```  
  with:
  ```  
    Check-For-Linked-Issue:
      runs-on: ubuntu-latest
      if: ${{ github.event.action == 'opened' }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Check for keyword and issue number
          id: check-for-keyword
          uses: actions/github-script@v7
          with:
            script: |
              const script = require('./github-actions/trigger-pr/check-linked-issue.js')
              script({g: github, c: context})
  ```  
- [x] In the directory [github-actions/trigger-pr/](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-pr) create a new file `check-linked-issue.js` with: 
  ```  
  // Import modules
  const postIssueComment = require('../utils/post-issue-comment');
  
  // Global variables
  var github;
  var context;
  
  async function main({ g, c }) {
    github = g;
    context = c;
  
    // Retrieve body of context.payload and search for GitHub keywords
    const prBody = context.payload.pull_request.body;
    const prNumber = context.payload.pull_request.number;
    const prOwner = context.payload.pull_request.user.login;
    const regex = /(?!<!--)(?:close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*#(\d+)(?![^<]*-->)/gi;
    const match = prBody.match(regex);
    let prComment;
  
    if (!match) {
      console.log('PR does not have a properly linked issue. Posting comment...');
      prComment = `@${prOwner}, this Pull Request is not linked to a valid issue. Above, please provide a valid linked issue in the format of 'Fixes #' + issue number, for example 'Fixes #9876'`;
    }
  
    else {
      let [ , keyword, linkNumber ] = match;
      console.log('Found a keyword: \'' + keyword + '\'. Checking for legitimate linked issue...');
  
      // Check if the linked issue exists in repo
      try {
        const response = await github.rest.issues.get({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: linkNumber,
        });
        console.log('Found an issue: \'#' + linkNumber + '\' in repo. Reference is a legitimate linked issue.');
      }
      catch (error) {
        console.log('Couldn\'t find issue #' + linkNumber + ' in repo. Posting comment...');
      prComment = `@${prOwner}, the issue number referenced above as "**${keyword}  #${linkNumber}**" is not found. Please replace with a valid issue number.`;
      }
    }
  
    // Comment on PR if no legit, linked issue (i.e. if prComment exists)
    if (prComment) {
      postIssueComment(prNumber, prComment, github, context);
    }
  }
  
  module.exports = main;  
  ```  

### Resources/Instructions
- Initiated by issue #6929
