### ISSUE TITLE
Add Heart project to new website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#72]
Here is the content for the file to be called heart.md.  
This file needs to go into the gh-pages _projects folder
```
---
title: Heart
description: Heart is a project working directly with the LA City Attorney’s Homeless Engagement and Response Team. The HEART program helps homeless individuals resolve eligible traffic and pedestrian infractions and related warrants and fines by engaging with relevant services. Hack for LA is helping them build a database and case management system to streamline their workflow and enable them to scale their program.
image: /assets/images/projects/heart.png
links:
  - name: Github
    url: https://github.com/hackforla/heart
 #  - name: Site
 #    url:
 - name: Slack channel
    url: https://hackforla.slack.com/messages/CDWKEBYBB
looking: experienced full-stack developer, node.js / react
location: Santa Monica
partner: LA City Attorney’s Homeless Engagement and Response Team
---
```
This is the image that needs to be called heart.png and put into the gh-pages folder /assets/images/projects
![heart](https://user-images.githubusercontent.com/37763229/56943529-c1e2fb80-6ad4-11e9-9445-21e121f53ddc.png)
