### ISSUE TITLE
Update Project Profile: Website Leadership (Will Gillis)

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7283]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want the Leadership information on our Website project to accurately represent the leadership structure of our team. Since Roslyn Wythe is the lead for the team, her information should be presented beside Bonnie's.

### Action Items
- [x] Go to the [Hack for LA Site](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md) project's markdown page and identify the `leadership` section. 
- [x] Select the entirety of the entry for Will Gillis:
   - [ ]  There may be an additional line with the key github-handle.  If so, that should be included in the selection
```
- name: Will Gillis
    role: Developer Co-Lead
    links:
      slack: 'https://hackforla.slack.com/team/U043LGHSZFT'
      github: 'https://github.com/t-will-gillis'
    picture: https://avatars.githubusercontent.com/t-will-gillis
```
- [x] **Move** the entry from the current location in the markdown file to the line after Bonnie's entry and any "Role: Product Manager" and/or "Role: Product Team" (e.g. Josiah Odosu), but before any "Role: Merge Team".
- [x]  Confirm on Docker that the entry appears correctly on the Website project page, and that no other, unexpected changes/ deletions/ etc. have been made.

### Resources/Instructions
[Hack for LA Site](https://www.hackforla.org/projects/website) project page
