### ISSUE TITLE
Add Heart project to old/currently-live website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#73]
Here is the content to be added to master static/content/index.md
```
  - dek: >-
      Heart is a project working directly with the LA City Attorney’s Homeless Engagement and Response Team. The HEART program helps homeless individuals resolve eligible traffic and pedestrian infractions and related warrants and fines by engaging with relevant services. Hack for LA is helping them build a database and case management system to streamline their workflow and enable them to scale their program.
    image: /images/uploads/heart.png
    links:
      - name: Github
        url: 'https://github.com/hackforla/heart'
      - name: Slack channel
        url: 'https://hackforla.slack.com/messages/CDWKEBYBB'
    looking: >-
      Experienced full-stack developer, node.js / react
    title: Heart
    location: Santa Monica
    Partner: LA City Attorney’s Homeless Engagement and Response Team
```
This is the image that needs to be called heart.png and put into the folder master static/images/uploads/
![heart](https://user-images.githubusercontent.com/37763229/56943529-c1e2fb80-6ad4-11e9-9445-21e121f53ddc.png)
