### ISSUE TITLE
Add additional GitHub field and TWE to Project Profile Card issue template

### ISSUE THREAD

**Issue by daras-cu** [hackforla/website#7363]
### Overview
In the "Project Profile Card review and update" issue template, we need to add options for Tech Work Experience and a field to submit additional GitHub repositories used by project volunteers. This will ensure issues can be submitted for the TWE project card and enable us to more accurately track a project's resources.

### Action Items
 - [x] Open `.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml` in your IDE.
 - [x] In the `Project Name` dropdown section, add `- "Tech Work Experience"` to the options list after `- "Open Community Survey"`, making sure the indentation matches the other list items.
 - [x] In the 'Project Card URL' dropdown section, add `- "tech-work-experience.md"` to the options list after `- "tdm-calculator.md"`, making sure the indentation matches the other list items.
 
Under the `Update GitHub Link` field ending with the lines:
 ```
attributes:
  label: GitHub Link 
```
- [x] Add the following code:
```
  - type: dropdown
    id: additional-github-repos-yes-no
    attributes:
      label: "Do you have any additional (other than your primary) GitHub repositories that your volunteers make issues or PRs against?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: additional-github-repos
    attributes:
      label: "If yes, list the repo URLs here"
```
- [x] Make sure to verify the indentation of each line uses spaces, not tabs, and matches the indentation pattern of the other fields in the file.
- [x] Ensure you have Issues enabled in your fork of the website repo on GitHub, and test opening a new issue with the Project Profile Card template to ensure the additional GitHub field shows up correctly.
- [x] Have Bonnie (@ExperimentsInHonesty) test the template changes by using it to submit the following changes for Tech Work Experience:
    - add another repo to pull contributors from

### Resources/Instructions
- New issue template [Project Profile Card review and update](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
- This issue initiated by #6863
