### ISSUE TITLE
Update Project Profile: VRMS Add Stephanie Samuels

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/website#7486]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `_projects/vrms.md` file.
- [ ] Observe the existing syntax of the front matter block [^1] in the file.
- [ ] Find the `leadership` variable and add the following profile. 
```
  - name: Stephanie Samuels
    github-handle: Steph112792
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U03SJS7LYCC
      github: https://github.com/Steph112792
    picture: https://avatars.githubusercontent.com/Steph112792
```
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] vrms page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/vrms
[^3]: initiating ER:  #7407
