### ISSUE TITLE
Update CoP: Ops: Remove Jennifer Nguyen

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#7567]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/ui-ux.yml` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and remove
```
  - name: Jennifer Nguyen
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U04K89GRNDS
      github: https://github.com/nguyen-jenn
    picture: https://avatars.githubusercontent.com/nguyen-jenn
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Community of Practice page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/communities-of-practice
- initiating ER:  #7087
