### ISSUE TITLE
Update Project Profile: LA TDM Calculator Remove Jane He

### ISSUE THREAD

**Issue by theogguu** [hackforla/website#7652]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/tdm-calculator.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x]  Find the `leadership` variable and remove the following:
```
  - name: Jane He
    github-handle:
    role: Lead, UX Research
    links:
      slack: 'https://hackforla.slack.com/team/U01RDSRT46R'
      github: 'https://github.com/Jane4925'
    picture: https://avatars.githubusercontent.com/Jane4925
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] LA TDM Calculator page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/tdm-calculator
-  initiating ER:  #7305
