### ISSUE TITLE
Update Project Profile: Civic Tech Jobs Remove Benny Van

### ISSUE THREAD

**Issue by floydferrer** [hackforla/website#7735]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [ ] Observe the existing syntax of the front matter block [^1] in the file.
- [ ]  Find the `leadership` variable and remove the following:
```
- name: Benny Van
    github-handle:
    role: Developer
    links:
      slack: https://hackforla.slack.com/team/U05JP90EHMK
      github: https://github.com/bennyv8
    picture: https://avatars.githubusercontent.com/bennyv8
```
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] Civic Tech Jobs page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: (https://www.hackforla.org/projects/civic-tech-jobs)
- initiating ER:  #7490
