### ISSUE TITLE
Update Project Profile: Website Remove Kelly Chuang

### ISSUE THREAD

**Issue by DrAcula27** [hackforla/website#7750]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `_projects/website.md` file.
- [ ] Observe the existing syntax of the front matter block [^1] in the file.
- [ ]  Find the `leadership` variable and remove the following:
```
  - name: Kelly Chuang
    github-handle: kellyc9
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U06REBB5K4M
      github: https://github.com/kellyc9
    picture: https://avatars.githubusercontent.com/kellyc9
```
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] Website page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/website
- initiating ER:  #7661
