### ISSUE TITLE
Update Project Profile: Website Add Daniel Franco and Kristen Cardon, Reorder Product Managers

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7824]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/website.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable, and then the entries for "Amen Divine Ikamba", "Samhitha Kamma", and "Priyanka Jujjavarapu". Move these entries up the list and place after the last "role: Product Manager" entry, but before the first "role: Developer Co-Lead" entry.
- [x] Add the following profiles to the end of the `leadership` list:  

```
  - name: Daniel Franco
    github-handle: FamousHero
    role: Merge Team
    links:
      slack: https://hackforla.slack.com/team/U076AV5ALPP
      github: https://github.com/FamousHero
    picture: https://avatars.githubusercontent.com/FamousHero
  - name: Kristen Cardon
    github-handle: k-cardon
    role: Merge Team
    links:
      slack: https://hackforla.slack.com/team/U07HCNXLCKH
      github: https://github.com/k-cardon
    picture: https://avatars.githubusercontent.com/k-cardon
```
- [x] Verify the changes and confirm the links by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Website page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/website
