### ISSUE TITLE
Update Project Profile:  VRMS Add Jack Haeger

### ISSUE THREAD

**Issue by mademarc** [hackforla/website#7848]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/vrms..md` file.
- [x] Observe the existing syntax of the front matter block .
- [ ] Find the `leadership` variable and add the following profile. 
```
  - name:Jack Haeger
    github-handle: JackHaeg
    role: Lead Product Manager
    links:
      slack: https://hackforla.slack.com/team/U059005TN1
      github: https://github.com/JackHaeg
    picture: https://avatars.githubusercontent.com/JackHaeg
```
- [ ] Verify the changes by viewing the VRMS project page on your local environment and include before and after screenshots with your pull request:
  - [ ] (https://www.hackforla.org/projects/vrms.html) page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/vrms.html
[^3]: initiating ER:  ##7407
