### ISSUE TITLE
Update Project Profile: Website Add Amen Divine Ikamba

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#7855]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/website.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile to the end after other "Merge Team" members:
```
  - name: Amen Divine Ikamba
    github-handle: amen-ikamba
    role: Product Manager - Dashboards
    links:
      slack: https://hackforla.slack.com/team/U07T35HCHAN
      github: https://github.com/amen-ikamba
    picture: https://avatars.githubusercontent.com/amen-ikamba
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Website page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/website)
