### ISSUE TITLE
Update Project Profile: VRMS updated `Github Handle and Role` of  Trillium Smith

### ISSUE THREAD

**Issue by belunatic** [hackforla/website#7879]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
- We need to keep project information up to date so that visitors to the website can find accurate information.
- This issue is related to issue #7357, so you can assign yourself to this issue and do both.

### Action Items
- [x] In your IDE, open the `_projects/vrms.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and revise the following profile by. 

Replacing:

```
- name: Trillium Smith
    role: Developer
    links:
      slack: 'https://hackforla.slack.com/team/U010G9864Q1'
      github: 'https://github.com/Spiteless'
    picture: 'https://avatars.githubusercontent.com/Spiteless'
```

With this:

```
  - name: Trillium Smith
    github-handle: trillium
    role: Lead Developer
    links:
      slack: https://hackforla.slack.com/team/U010G9864Q1
      github: https://github.com/trillium
    picture: https://avatars.githubusercontent.com/trillium
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] VRMS page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/vrms
[^3]: initiating ER:  #7407

**Comment by belunatic** [comment]
please ping me in Slack if you have any question on this issue. My name is Abel Sila

**Comment by ExperimentsInHonesty** [comment]
@belunatic this issue is a special case.  Because it's an update, you would need to indicate what the prior content in the page was and that they should replace it with the new content.  Please update the top portion of this issue.

Here is the current content
https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md?plain=1#L54C1-L59C63
```
  - name: Trillium Smith
    role: Developer
    links:
      slack: 'https://hackforla.slack.com/team/U010G9864Q1'
      github: 'https://github.com/Spiteless'
    picture: 'https://avatars.githubusercontent.com/Spiteless'
```
