### ISSUE TITLE
Update Project Profile: Home Unite Us Add Ariel Lasry

### ISSUE THREAD

**Issue by mademarc** [hackforla/website#7909]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `home-unite-us.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile at the top of the list of profiles. 
```
  - name: Ariel Lasry
    github-handle: lasryariel
    role: Product Manager (Lead Persona)
    links:
      slack: https://hackforla.slack.com/team/U06MG4S8D2B
      github: https://github.com/lasryariel
    picture: https://avatars.githubusercontent.com/lasryariel
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] home-unite-us.md page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/home-unite-us
[^3]: initiating ER:  #7362
