### ISSUE TITLE
Update Project Profile: Home Unite Us Add Jasika Kalra

### ISSUE THREAD

**Issue by mademarc** [hackforla/website#7921]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `home-unite-us.md` file.
- [ ] Observe the existing syntax of the front matter block [^1] in the file.
- [ ] Find the `leadership` variable and add the following profile. 
```
  - name: [Insert leadership member's name]
    github-handle:j asika-ai
    role: Product Manager (Lead Persona)
    links:
      slack: https://hackforla.slack.com/team/U03J4C686KV
      github: https://github.com/jasika-ai
    picture: https://avatars.githubusercontent.com/ jasika-ai
```
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] Home Unite Us page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL:https://www.hackforla.org/projects/home-unite-us)
[^3]: initiating ER:  # #7362
