### ISSUE TITLE
Update Project Profile: Website- change Danielle Aras to Co-Lead

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7938]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/website.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] First, **_replace_** the `leadership` variable for the following profile: 
  ```
    - name: Danielle Hanson Aras
      github-handle:
      role: Merge Team
      links:
        slack: 'https://hackforla.slack.com/team/U076DT96PUJ'
        github: 'https://github.com/daras-cu'
      picture: https://avatars.githubusercontent.com/daras-cu
  ```  
  with:
  ```
    - name: Danielle Hanson Aras
      github-handle: daras-cu
      role: Developer Co-Lead
      links:
        slack: 'https://hackforla.slack.com/team/U076DT96PUJ'
        github: 'https://github.com/daras-cu'
      picture: https://avatars.githubusercontent.com/daras-cu
  ``` 
- [x] Then, **_move_** Danielle Hanson Aras' profile up the list so that it is with the other "Developer Co-Lead" profile(s).
- [x] Verify the changes by viewing the Hack for LA Website project page[^2] in your local environment, and include before and after screenshots with your pull request.

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: [Hack for LA Site](https://www.hackforla.org/projects/website)
