### ISSUE TITLE
Update Project Profile: Website- add Mugdh Chauhan to Merge Team

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7939]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/website.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and **_add_** the following profile to the end of the list: 
  ```
    - name: Mugdh Chauhan
      github-handle: mugdhchauhan
      role: Merge Team
      links:
        slack: 'https://hackforla.slack.com/team/U08041Y2E72'
        github: 'https://github.com/mugdhchauhan'
      picture: https://avatars.githubusercontent.com/mugdhchauhan
  ```  
- [x] Verify the changes by viewing the Hack for LA Website project page[^2] in your local environment, and include before and after screenshots with your pull request.

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: [Hack for LA Site](https://www.hackforla.org/projects/website)
