### ISSUE TITLE
Update Project Profile: Civic Tech Jobs- Add Janis Mollineau

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7997]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [ ] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [ ] Observe the existing syntax of the front matter block [^1] in the file.
- [ ] Find the `leadership` variable and **_insert_** the following profile between the last "Product Manager" and the first "Developer Lead":
```
  - name: Janis Mollineau
    github-handle: Janis-Mollineau
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U088EKFQJCD
      github: https://github.com/Janis-Mollineau
    picture: https://avatars.githubusercontent.com/Janis-Mollineau
```
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] Civic Tech Jobs page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs)
- Initiating ER: #7867
