### ISSUE TITLE
Update Project Profile: Civic Tech Jobs Remove Kanika Chotani and Jimmy Juarez

### ISSUE THREAD

**Issue by Six5pAdes** [hackforla/website#8084]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x]  Find the `leadership` variable and remove the following:
```
  - name: Kanika Chotani
    github-handle: kchotani
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U02E7ATACAV
      github: https://github.com/kchotani
    picture: https://avatars.githubusercontent.com/kchotani
```
```
  - name: Jimmy Juarez
    github-handle: JimmyJuarez10
    role: Developer Lead
    links:
      slack: https://hackforla.slack.com/team/U062FQ7UXQE
      github: https://github.com/JimmyJuarez10
    picture: https://avatars.githubusercontent.com/JimmyJuarez10
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
