### ISSUE TITLE
Update Project Profile: Civic Tech Jobs - Add Snigdha Tiwari

### ISSUE THREAD

**Issue by jphamtv** [hackforla/website#8110]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x]  Find the `leadership` variable and add the following after the Product Manager roles:
```
  - name: Snigdha Tiwari
    github-handle: snigdhat1
    role: Developer Lead
    links:
      slack: https://hackforla.slack.com/team/U08N4CKKJUW
      github: https://github.com/snigdhat1
    picture: https://avatars.githubusercontent.com/snigdhat1
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
- Initiating ER: #8100
