### ISSUE TITLE
Update CoP: Ops - Add Brittany Sims

### ISSUE THREAD

**Issue by jphamtv** [hackforla/website#8120]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/ops.yml` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Brittany Sims
    github-handle: brittanyms
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U06E9RFGE5A
      github: https://github.com/brittanyms
    picture: https://avatars.githubusercontent.com/brittanyms
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Communities of Practice page [^2]

### Resources/Instructions
- Initiating ER: #7905 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/communities-of-practice
