### ISSUE TITLE
Replace external GHA module with internal `check-team-membership.js utility`

### ISSUE THREAD

**Issue by xnealcarson** [hackforla/website#8151]
### Overview
We need to refactor the "Issue Trigger" workflow to replace the external `tspascoal/get-user-teams-membership` with our existing, internal `check-team-membership.js` module.

### Details

Reasons for making these changes:

- We already have the `check-team-membership.js` utility, so we should use it.
- With the external module, we are relying on someone outside of the organization to keep the code current.
- If we use the internal `utility function`, we are able to eliminate the `TEAMS` secret & `TEAMS` token.
 - Reorder of the workflow steps so that team membership is checked first since this is the controlling step.

### Action Items
- [x] Refactor the [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) file. The following code is suggested:

Replace:  
  ``` 
      - uses: actions/checkout@v4    
      # Check if the issue has required labels
      - name: Check Labels
        id: check-labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_GRAPHQL_TOKEN }}
          script: |
            const script = require('./github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js')
            const checkLabels = script({g: github, c: context})
            return checkLabels
            
      # Checks if user is on the 'website-write' team
      - uses: tspascoal/get-user-teams-membership@v3
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          organization: 'hackforla'
          team: 'website-write'
          GITHUB_TOKEN: ${{ secrets.TEAMS }}

      # Posts comment only if user is team member (based on the previous action's result)
      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
        name: Post Comment
        uses: actions/github-script@v7
        id: post-comment
  ```  
  with:  
  ```  
      - uses: actions/checkout@v4   
      # Checks if user is on the 'website-write' team, else halts workflow
      - name: Check Team Membership
        id: check-team-membership
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HACKFORLA_GRAPHQL_TOKEN }}
          script: |
            const username = '${{ github.actor }}'
            const team = 'website-write'
            const script = require('./github-actions/utils/check-team-membership.js')
            return script(github, username, team)
            
      # If user is team member: checks if the issue has required labels
      - if: ${{ steps.check-team-membership.outputs.result == 'true' }}
        name: Check Labels
        id: check-labels
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js')
            const checkLabels = script({g: github, c: context})
            return checkLabels
                  
      # If user is a team member: posts comment
      - if: ${{ steps.check-team-membership.outputs.result == 'true' }}
        name: Post Comment
        id: post-comment
        uses: actions/github-script@v7
  ```  
  
- [x] Test the replacement code for internal utility functionality
- [x] **FOR MERGE TEAM** : remove both the TEAMS token and the TEAMS secret after merging.
  - Re: #8200 

### Resources/Instructions
- [preliminary-update-comment.js](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js).
- Refer to https://github.com/hackforla/website/issues/6537#issuecomment-2041147335, especially Tips 6, 7, and 8, if you have not already created you personal environment for testing.
- [How to Test GitHub Actions](https://drive.google.com/drive/u/0/folders/1MPY9CKcfKKN7hpDCG46ARrRzRSM8d8OA)
- [Additional Notes for GitHub Actions](https://docs.google.com/document/d/1frtvr5twBa_3yRGCG0divhlOMW8dPJxT/edit)
- This issue initiated by #8024
